clients/callback_client.go, clients/callback_client_test.go, config/config.go, config/timestamp.go
Currently implementing Transcode Status success / error based on spec in https://www.notion.so/livepeer/Technical-Design-Studio-Catalyst-API-for-VOD-Recording-bba2b160efff4ad4963dae2d4e9ff1a2
Completion Outputs block (i.e telling Studio where we've put the files) will come in a separate PR
=> Add HTTP callback client for communicating status to Studio

handlers/client.go
This was failing because one of the fields isn't a string but we were trying to parse it as one. 
Switched to only parsing the field we care about, which should be safer if other fields appear here in the future.
```json
{
"local": true,
"status": "OK"
}
```
=> Parse Mist auth response correctly

clients/callback_client.go, clients/callback_client_test.go, go.mod, go.sum
We were getting errors because of not resetting the POST body correctly before retrying, so decided to switch to a library and not have to think about that stuff.
=> Switch to HTTP retry library

clients/callback_client.go, handlers/handlers.go
This is so we can do any final iterations on how the output will look and slightly unblock Studio
=> Stub "Transcode Complete" callback

.github/workflows/golangci-lint.yml, Makefile, README.md, api/http.go, clients/callback_client_test.go, errors/errors.go, handlers/ok.go, handlers/transcode.go, handlers/triggers.go, handlers/upload.go, middleware/logging.go
Let's try and lint from the start of this project
=> Add linting as CI step

config/config.go, handlers/misttriggers/push_end.go, handlers/misttriggers/triggers.go, handlers/misttriggers/triggers_test.go, handlers/upload.go
The number of required functions are growing. Preparing for recording pipeline changes, lets define new constants for each pipeline. In trigger handling we can use stream prefix to determine to which function a stream belongs to.
Changes:
- Define pipeline constants
- Triggers: Use switch to branch to proper pipeline logic based on stream name
- Move string constant from UploadVOD() to config
=> Define pipeline constants

config/config.go
See livepeer/catalyst@83d3bcd4d8aa52795cb27883605bcf7e5a0d3dcc
MistProcLivepeer needs to be invoked in /usr/local/bin after the above commit that changes where MistController is invoked from.
=> config: MistProcLivepeer in /usr/local/bin/

handlers/misttriggers/live_tracklist.go
Change rendition URL from:
```
s3+https://GOOG:pass@storage.googleapis.com/alexk-dms-upload-test/bbb/segmented/tr_rend_+_bbfaegff_428x240/stream.m3u8
```
into:
```
s3+https://GOOG:pass@storage.googleapis.com/alexk-dms-upload-test/bbb/segmented/_bbfaegff_428x240/stream.m3u8
```
=> Remove RENDITION_PREFIX from push URL

config/config.go, handlers/misttriggers/push_end.go, handlers/misttriggers/triggers_test.go, handlers/transcode.go, subprocess/logging.go
Config `config.PathMistDir` now contains path to MistServer binaries directory. We use this info to construct absolute path to `MistProcLivepeer` and `MistInHLS`.
`MistInHLS` is used to create `.dtsh` headers file alongside playlist and segments created on s3.
https://github.com/DDVTECH/mistserver/issues/117 is created for tracking MistServer issue that will obsolete this extra step of running `MistInHLS`.
Add subprocess/logging.go
=> Run MistInHLS mist binary on push end for each rendition

cache/segmenting.go, cache/segmenting_test.go, handlers/misttriggers/live_tracklist.go, handlers/misttriggers/push_end.go, handlers/misttriggers/triggers.go, handlers/transcode.go, handlers/upload.go
Puts all transcoded segments + manifests under a `transcoded/` dir, rather than alongside the source MP4.
Doesn't account for multiple output locations yet, but is enough for us to test with.
=> Upload transcodes to output target location rather than input location

handlers/upload.go
We don't need to dynamically add PUSH_END trigger in catalyst-api - this results in double the amount of transcode renditions as Mist iterates through the triggers list.
#/Fix https://github.com/livepeer/catalyst/issues/201
#/Fix https://github.com/livepeer/catalyst-api/issues/60
=> handlers/upload: use PUSH_END trigger as configured in Mist config

cache/transcoding.go, cache/transcoding_test.go, main.go
This doesn't do the checking of transcode progress with Mist, but does provide the framework where we'd slot that in.
For now, if an item is in the "Transcode" cache, we update Studio every 15 seconds. I'd guess this is also going to expose some bugs where we're not removing things from the cache when we should be.
=> Add callback heartbeats for in-flight transcodes

cache/transcoding.go, cache/transcoding_test.go, main.go
This should stop us from hammering Studio with useless callbacks if there are cases where we're not correctly removing completed / errored jobs from the cache.
We can also monitor the logs for the logged message to figure out if this is happening.
=> Expire objects from cache after 1hr

handlers/misttriggers/push_end.go, handlers/transcode.go, handlers/upload.go
* remove harcoded-broadcaster fields in the incoming request as it is not an option that will be used
* add hardcoded-broadcaster as the fallback option if access-token is not provided in the incoming request
=> handlers: allow hardcoded B to be used by MistProcLivepeer

handlers/upload.go
Studio is not expected to know the extension types of the files uploaded by the end user. As such, Studio can provide urls without any file extensions like mp4/mov. However, Mist requires file extensions to guess what type of input process to spawn (e.g. MistInMP4).
For now, we only care about mp4/mov file input - so we force all input URLs to mp4 format by using the "mp4:" override in front of an URL identifier so the it reads: "mp4:s3+http://example-url.com/video"
=> handlers: force mp4 override for source URLs

handlers/upload.go
Reverts livepeer/catalyst-api#75
=> Revert "handlers: force mp4 override for source URLs"

handlers/upload.go
Reverts livepeer/catalyst-api#77
=> Revert "Revert "handlers: force mp4 override for source URLs""

cache/segmenting.go, cache/transcoding.go, go.mod, go.sum
It's nice to see print the cache contents when things are stored/deleted from the cache - makes debugging certain situations easier.
=> cache: print cache for easier debugging

transcode/manifest.go, transcode/manifest_test.go, transcode/transcode.go, transcode/transcode_test.go
Small change to split the manifest code out into its own file and iterate through the segment list, generating ObjectStore URLs that can be used by the transcoder and downloading those files into memory
=> Generate source segment URLs

clients/broadcaster.go, clients/broadcaster_local.go, clients/broadcaster_remote.go, clients/mist_client.go, handlers/misttriggers/recording_end.go, handlers/misttriggers/recording_end_test.go, handlers/transcode.go, transcode/manifest.go, transcode/manifest_test.go, transcode/transcode.go, transcode/transcode_test.go
If the access-token is provided in the transcode request, the remote broadcaster (via livepeer.com) will be used to transcode. Otherwise, the local broadcaster will be used to transcode.
=> transcode: trigger the transcode via remote or local broadcaster

clients/callback_client.go, clients/mist_client.go, handlers/misttriggers/recording_end.go
```json
"video_spec": {
"format": "mp4",
"tracks": [
{
"type": "audio",
"codec": "AAC",
"bitrate": 255856,
"duration": 6.24,
"size": 0,
"start_time": 0,
"channels": 2,
"sample_rate": 48000,
"sample_bits": 16
},
{
"type": "video",
"codec": "H264",
"bitrate": 10167032,
"duration": 6.219,
"size": 0,
"start_time": 0,
"width": 2048,
"height": 858
}
],
"duration": 6.218,
"size": 8279708
}
```
=> Populate source stream format info

handlers/misttriggers/recording_end.go, handlers/transcode.go, transcode/manifest.go, transcode/manifest_test.go, transcode/transcode.go, transcode/transcode_test.go
Resolves https://github.com/livepeer/catalyst-api/issues/99
=> Pass segment duration to transcoder instead of overall duration

clients/broadcaster.go, clients/broadcaster_local.go, transcode/manifest_test.go, transcode/transcode.go, transcode/transcode_test.go
This is the second part of a fix for https://github.com/livepeer/catalyst-api/issues/113
We were seeing very slow transcode times and lots of logs where the B was struggling to find an O because we were passing in a blank manifestID and so it 
was creating a new session for each segment.
=> Re-use Manifest ID with local B to avoid creating new sessions

transcode/manifest.go, transcode/manifest_test.go, transcode/transcode.go
Produced multivariant playlist now contains proper bitrate:
```m3u8
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-STREAM-INF:PROGRAM-ID=0,BANDWIDTH=2188957288,RESOLUTION=1280x720,NAME="0-720p",FRAME-RATE=30.000
rendition-0/rendition.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=0,BANDWIDTH=745890531,RESOLUTION=640x360,NAME="1-360p",FRAME-RATE=30.000
rendition-1/rendition.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=0,BANDWIDTH=3884863845,RESOLUTION=2048x858,NAME="2-source"
rendition-2/rendition.m3u8
```
=> calculating bitrate of transcoded results

handlers/handlers_test.go, handlers/upload.go, transcode/manifest.go, transcode/manifest_test.go, transcode/transcode.go, transcode/transcode_test.go
Fix https://github.com/livepeer/catalyst-api/issues/134
=> Update directory tree of output segments from VoD pipeline

clients/broadcaster.go, transcode/transcode.go
This is to make some improvements to the asset profile generation logic, leveraging
from the existing logic in `task-runner` today. 
Main changes: 
- There's a longer list of default profiles, but those are filtered out depending on the source video
- With that, changed the logic on including the source profile in the output. It's always added now (since there will be no profile equal or better than it from the above process)
=> transcode: Improve asset transcoded profiles

go.mod, go.sum
Reverts livepeer/catalyst-api#138
=> Revert "Bump github.com/minio/madmin-go from 1.6.6 to 1.7.3"

handlers/upload.go, log/logger.go
I'd missed that the cache has an "Add" and a "Replace" method and fails if you're using the first when the object exists / the second when it doesn't.
=> Fix contextual logging

transcode/manifest.go, transcode/manifest_test.go, transcode/transcode.go, transcode/transcode_test.go
Instead of rendition-* folder names, use the profile name (e.g. 720p,
1080p, etc) as the folder name to make it more user friendly.
=> Update transcoded rendition folder names

transcode/manifest.go, transcode/manifest_test.go, transcode/transcode.go, transcode/transcode_test.go
Remote B (via access-token) rejects transcode request if a profile with name "source" is used. The "source" keyword is used to define an incoming RTMP push in go-livepeer (server/mediaserver.go) - which triggers a different use-case. Change the profile name to follow the name syntax (e.g. 720p) being used for the other profiles.
=> transcode: update profile name for rendition that matches the source stream's resolution

handlers/misttriggers/recording_end.go
Only multivariant playlist .dtsh file is used in playback. Removing creation of renditions .dtsh files.
=> remove rendition .dtsh files

clients/callback_client.go, handlers/misttriggers/recording_end.go, transcode/transcode.go, transcode/transcode_test.go
First playback will fail via mistserver if .dtsh file is not present on S3.
Introducing `playback-ready` status callback when .dtsh file is created.
If studio is using mist playback then this additional callback signals ready state, if not then `success` (TranscodeStatusCompleted) signals ready state.
=> Send the success callback after dtsh upload

clients/broadcaster.go, clients/broadcaster_local.go
This is to be more lenient than the Live workflow when waiting for transcoders.
Broadcaster change in https://github.com/livepeer/go-livepeer/pull/2650
=> Send a Segment Upload Multiplier of 3 to local broadcaster

config/config.go, transcode/transcode.go, transcode/transcode_jobs.go, transcode/transcode_test.go
- Stop all workers on first error
- Fix progress calculation
- Unit tests
Fixes https://github.com/livepeer/catalyst-api/issues/173
=> Stop transcoding on first error

config/config.go
From the errors we've seen, it seems like we're overloading the Orchestrators. Scale back the parallelism to try and reduce this.
=> Reduce parallelism from 5 -> 2

transcode/transcode.go
This should hopefully also reduce Orchestrator load and some of the timeout errors we've been seeing
=> Reduce num of entries in default bitrate ladder

handlers/misttriggers/recording_end.go, handlers/misttriggers/triggers.go
For asset `4a452c8c-53d8-41a6-b5f5-695ba28cdf60` we see the job just stop with no output after receiving the RECORDING_END trigger. Suspicion is that something's different about the trigger.
=> Log trigger errors

errors/errors.go, handlers/handlers_test.go, handlers/upload.go
I thought we'd caught all of these, but looks like we were writing HTTP errors (but not returning) for callback failures
=> Fix 'http: wrote more than the declared Content-Length' error

clients/object_store_client.go, clients/object_store_client_test.go, config/config.go
Implement a constant backoff with 1 second interval and 15 retries for osclient.DownloadOSURL
Closes #209
=> Use constant backoff for DownloadOSURL

handlers/handlers_test.go, handlers/upload.go
This fixes a bug where if Arweave/IPFS copy takes too long, Studio times out
=> Fire first callback immediately

transcode/transcode.go
When the input video's height or bitrate combo is too low to meet the ABR ladder, the low-bitrate profile is used in addition to the input video's profile to have some ABR during playback. The low-bitrate profile 1/3's the input video profile resulting in pretty low quality video. Increase this to be 75% of the input video's resolution so that playback still feels good without experiencing artifacts.
\#fix https://github.com/livepeer/catalyst-api/issues/215
=> transcode: improve low-bitrate profiles bitrate slightly for better playback

clients/broadcaster.go, clients/broadcaster_local.go
This is the other half of https://github.com/livepeer/go-livepeer/pull/2667
=> Update timeout param name to reflect go-livepeer change

clients/mediaconvert.go, clients/transcode_provider.go
- Handle S3 vs S3 OS URLs properly. Turns out that it was not only the credentials that had to be removed. Created a helper in the struct with the already translated URL to make things simpler.
- Handle the 1042 error from MediaConvert and retry without acceleration
- Fixed OS hell as the list returns the full path of the file but the gets and writes interpret it as a relative path
=> clients/mediaconvert: Some final fixes to the mediaconvert pipeline

main.go
We were formatting the pointer value instead of the flag value.
=> cmd: Fix usage of mist port args

clients/mediaconvert.go, pipeline/external.go
Follow-up on #237. 
The error code is not the documented, it's a secret one 🙄 
Also fix a small issue in the external `pipeline.Handler`, which should have an output with
type `object_store` instead of `manifest` .
=> mediaconvert: Handle secret acceleration error code

handlers/upload.go, pipeline/coordinator.go, pipeline/mist.go
Found a bug on the background mist job: Since the coordinator only changes the TargetURL when the job is in background (line 206), the mist job will actually not pick up that change since it uses the segmenting URL instead.
Fix this the right way, by moving the creation of the segmeting URL to the mist pipeline. It is only used there.
The only small issue is that it is still a "global" field in the job info, so I added a comment that it's only used in mist for now. We can do something more sophisticated is this grows (like a "handler data" inside the job info struct that can be of any type)
=> handlers,pipeline: Move segmenting target URL logic to mist pipeline

.github/workflows/test.yaml
Create a separate test job for cucumber tests that run in parallel of unit tests. Seems to be room for improvement by sharing the build  and mod download cache between jobs.
Should close #213
=> Separate cucumber from unit tests

clients/mediaconvert.go
FTR: We have this same issue in the old task-runner and the new catalyst pipelines. We need to implement the same auto-rotate logic based on video metadata on the Catalyst pipeline.
=> clients/mediaconvert: Auto-rotate input video based on metadata

clients/mediaconvert.go
Documentation: https://docs.aws.amazon.com/sdk-for-go/api/service/mediaconvert/
Pricing: https://aws.amazon.com/mediaconvert/pricing/
=> Switch from 2 pass -> 1 pass encoding

clients/mediaconvert.go
Reverts livepeer/catalyst-api#287
=> Revert "Switch from 2 pass -> 1 pass encoding"

clients/arweave_ipfs_s3.go, clients/mediaconvert.go
Updates:
- Renamed `arweaveIPFSHttpClient` to `defaultRetryableHttpClient` since the configured retryable HTTP client is not Arweave & IPFS specific (although it happens to be particularly useful for fetching data from Arweave & IPFS because the first request for data with these gateways can fail or be slow)
- Use the `defaultRetryableHttpClient` when downloading a file during the copy operation to the S3 transfer bucket used for MC. The use of this client should ensure that we retry requests (up to 3 times with the current config) which should help (at least sometimes) with the recent 504 Gateway Timeouts that we've received from IPFS gateways. See [this comment](https://github.com/livepeer/task-runner/issues/79#issuecomment-1303709294) for additional context.
=> mediaconvert: Use retryable HTTP client for download during copying

clients/mediaconvert.go, clients/transcode_provider.go, handlers/transcode.go, metrics/metrics.go, pipeline/coordinator.go, pipeline/coordinator_test.go, pipeline/external.go, pipeline/mist.go, transcode/transcode.go, transcode/transcode_test.go
Initial implementation of VOD pipeline metrics
Not all metrics are collected for MediaConvert strategy. `vod_source_segments` and `vod_source_duration` are unavailable for that flow, same for the labels `source_codec_video` and `source_codec_audio`. We could use some ffprobe or mediainfo go library to populate them.
Please, make sure to review the metrics types https://github.com/livepeer/catalyst-api/pull/288/files#diff-d715f391f2ffa038c3167bfea1adf741c1f5e39f08349fbbacab780a594146a4R120, not sure if these are the right types to use.
=> Implement VOD pipeline metrics

clients/callback_client.go, clients/callback_client_status.go, clients/callback_client_status_test.go, clients/callback_client_test.go, handlers/handlers_test.go, pipeline/coordinator_test.go
This ensures that if we send a message with completion ratio X, we don't then repeatedly send a message with completion ratio < X.
The change itself is quite a small check in the code where we update our internal `Request ID -> Status` mapping, but I also updated our JSON mapping to be strongly typed rather than using a string for the Status Message.
=> Don't send callbacks out of order

.github/workflows/golangci-lint.yml
I've been seeing this step failing because of the timeout. Looks from https://github.com/golangci/golangci-lint-action/issues/297 like the default has just become a bit too short for the number of linters it runs.
=> Increase linting timeout from 1m (default) -> 3m

clients/mediaconvert.go, clients/mediaconvert_test.go, clients/object_store_client.go, clients/transcode_provider.go, clients/transcode_provider_test.go
As part of tech debt week, I'm adding some unit tests to the MediaConvert client here.
Only some minimal changes to the actual core code, from some things I needed to change
to make the tests work to some minor issues I found on the code and could fix as well.
Added tests for some basic error cases as well as full successful run, using only temp local
files for the tests.
=> clients: Create some tests for the mediaconvert client

.github/workflows/golangci-lint.yml, clients/mediaconvert.go
Introduce `requestID` into the transfer bucket path for MediaConvert. 
Before, we didn't use any randomness in the path. That was not an issue while using assets in Studio, because Studio creates a random ID for each asset. However, it became an issue while introducing Transcode API, where users can define their own output directory. Without any randomness, one request could overwrite another requests.
fix https://github.com/livepeer/catalyst/issues/344
=> Use requestID in the transfer bucket path

pipeline/coordinator.go, pipeline/coordinator_test.go
To address https://github.com/livepeer/catalyst-api/issues/278
Column changes:
- renaming `timestamp` to `finished_at`
- adding `started_at`, `source_url` and `target_url`
=> add new postgres metrics fields

pipeline/mist.go
Google S3 source URLs have content-type as follows:
`content-type: application/octet-stream`
Only check content-type for video tags when arweave/ipfs URLs are detected.
#\fix 369
=> mist: check content-type header for video tag for arweave/ipfs urls only

pipeline/mist.go, pipeline/mist_test.go
This is just to make it match up with our current implementation
=> Remove seg_ prefix from Mist target URL

clients/fixtures/mediaconvert_payloads/happy.txt, video/profiles.go
Trying this out to see if we can improve our Livepeer pipeline transcodes
=> Bump maximum bitrate for default profiles

video/profiles.go, video/profiles_test.go
Previously the `lowerQualityThanSrc` condition would match if the heights were equal, which would result in a duplicate profile because we are then adding a profile with height equal to the input [lower down in the function](https://github.com/livepeer/catalyst-api/compare/mh/fix-duplicate-profile?expand=1#diff-7bbc069c84bd3dadf5c408f6c62b025837d72035cd18c8cea4b70a4d12efd1c1R104)
E.g. you'd end up with a set of profiles like:
```
{Name: "360p0", Width: 640, Height: 360, Bitrate: 800_000},
{Name: "720p0", Width: 1280, Height: 720, Bitrate: 3_000_000},
{Name: "720p0", Width: 1280, Height: 720, Bitrate: 3_000_001},
```
MediaConvert errors on this because the output paths clash (due to the duplicate profile name).
=> fix duplicate profile

clients/callback_client_status.go, clients/mediaconvert.go
if copying from dstorage failed we were then attempting to get a presigned s3 url from a non existent object
=> remove logic to let MC try dstorage urls

clients/mediaconvert.go
the extra mp4 outputs in the message were causing a nil panic in task-runner
=> revert studio message change

clients/mediaconvert.go, clients/mediaconvert_test.go, video/probe.go
this was misleading as it is actually the total file size (video and audio) we were not using the field anywhere anyway
=> dont set video track size

video/probe.go, video/probe_test.go
Any single jpeg input file may get classified as an mjpeg in the probing logic. These inputs are not supported currently. This change adds a check for mjpeg type of inputs and fails the probe check.
=> probe: add check for jpeg/mpeg type of inputs

config/config.go, middleware/capacity.go, middleware/capacity_test.go
Now that we're more confident in the system, we'll bump this and monitor error rates. 5 -> 8 should still be conservative given the CPU + Memory headroom we have.
=> Bump concurrent capacity from 5 -> 8

clients/mediaconvert.go, clients/mediaconvert_test.go, clients/transcode_provider.go, handlers/upload.go, handlers/upload_test.go, pipeline/coordinator.go, pipeline/external.go
only generate mp4s if auto_mp4 request flag is set and input duration is less than 2mins
Fixes https://github.com/livepeer/catalyst-api/issues/418
=> introduce auto_mp4 request flag

video/profiles.go, video/profiles_test.go
Mediaconvert only accepts even values for width and height so we have to round these values.
We were seeing the following errors in the logs:
`Invalid resolution [400 x 239], only even values are supported. video_description [1]`
=> round to an even height and width to fix MC errors

clients/input_copy.go, clients/mediaconvert.go, clients/mediaconvert_test.go, clients/upload.go, log/logger.go, log/logger_test.go
Moving the logic which copies the input to s3 and probes it into a separate file. We'll then be able to use this for the mist pipeline too.
=> extract s3 upload and probe into a function

clients/arweave_ipfs_s3.go, clients/input_copy.go
Some ipfs URLs can be downloaded successfully but closer inspection of the files on S3 reveals only a few kB as being downloaded and uploaded. Add logging to try and root-cause this issue of incomplete uploads.
=> clients: add logging to dstorage download flow

video/probe.go
By default the log level through the ffprobe library we're using is set to "fatal", this seems to be too high since we have never seen an error message printed when we get a probe failure, just a generic message like:
`error running ffprobe [] exit status 1`
if we switch to level "error" we will start to see more detail like:
`error running ffprobe [/Users/max/Downloads/video: Invalid data found when processing input] exit status 1`
=> Switch probe log level to error

clients/input_copy.go, clients/mediaconvert.go
Moving copy functions to `input_copy.go` as they'll now be used for the mist pipeline too.
=> Move copy functions to input_copy

clients/input_copy.go
When we start supporting mp4 output, then the current timeout for saving data (`5 min`) may not be high enough. This PR increases this timeout.
However, I think we could think about an approach in which the timeout actually depends on the file size. @emranemran @victorges wdyt?
Also a comment from @emranemran 
> Will this cause issues with Studio timeouts?
https://github.com/livepeer/studio/blob/23b1aa453bbef83981ad2547169c7149f0436e35/packages/api/src/store/task-table.ts#L7-L9
If we're stuck in UploadToOSURL, is our callback to Studio ReportProgress called concurrently?
cc @victorges
=> Increase the timeout for mediaconvert to support big mp4 files

main.go, pprof/pprof.go
We're having some errors copying output files to storage so adding a pprof listener to be able to retrieve profiling/tracing data from the pods to investigate.
=> Add a pprof listener for tracing

clients/arweave_ipfs_s3.go, clients/input_copy.go, clients/mediaconvert.go, clients/mediaconvert_test.go, clients/object_store_client.go, clients/object_store_client_test.go, transcode/manifest.go, transcode/transcode.go
I discovered that our current upload retry mechanism is fundamentally wrong and therefore it **does not work**. This PR fixes the issue.
fix #473 
One non-backward-compatible change is that we'll no longer have the upload retries metrics.
---------
**Explanation**
We retry saving the data here:
https://github.com/livepeer/catalyst-api/blob/main/clients/object_store_client.go#L75
But what we pass is `data io.Reader` which is not something you can retry, because if some data was already read from the reader, then it's not there anymore. Therefore it does not make sense to have any retry mechanism in the `UploadToOSURL()` function. 
This PR moves the retry mechanism from the `UploadToOSURL()` function upper to the place where it can actually be retried.
=> Fix retry mechanism

video/profiles.go, video/profiles_test.go
- mediaconvert was throwing an error when an input had a very high bitrate, over 288000000
- renamed constants to match the golang convention
=> Set a maximum bitrate for our output renditions

clients/arweave_ipfs_s3.go, clients/input_copy.go, clients/object_store_client.go, transcode/manifest.go, transcode/transcode.go
We were seeing intermittent data race failures in our unit tests. This backoff implementation is advertised as not thread safe so we need a new instance each time. https://github.com/cenkalti/backoff/blob/v4.2.0/tries.go#L10-L12
=> Fix data race

clients/input_copy.go
I realised that there is some retry logic for the probing ahead of the presigned URL being sent to MediaConvert, so I think it's safer to increase the validity period a bit in case it expires by the time MediaConvert reads it.
=> Increase presigned url expiry

clients/mediaconvert.go, clients/mediaconvert_test.go, clients/transcode_provider.go, pipeline/coordinator.go, pipeline/external.go, pipeline/mist.go, transcode/transcode.go
The AutoMP4 field in the studio request and the input file's duration is checked to enable MP4 generation -- this is currently only implemented for the mediaconvert pipeline. This commit moves the check and decision to HandleStartUploadJob such that it applies to both MediaConvert and Livepeer pipelines.
TODOs: 
* fix tests
=> transcode: commonize mp4 flag between pipelines

clients/arweave_ipfs_s3.go, clients/arweave_ipfs_s3_test.go, main.go
We were ignoring the path of the incoming IPFS urls which meant we were fetching directory/contents pages rather than the intended files. From testing it appears that if we concatenate the host and path we get the correct result, for IPFS urls without any path this continues to work fine.
(Also removed an unused function in main.go)
=> Fix IPFS resource ID parsing

handlers/debug.go, main.go
This is to allow us to check the internal state of the app while it's running. Initially to be able to check the current jobs being processed
=> Add a debug endpoint

transcode/transcode.go, video/media.go
The segments returned from the T are first stored in the order they are
received, and then sorted according to the segment index, and then
concatenated into a single .ts file. A nested map with an outer and
inner table is used to temporarily store the segment data streams.
TODOs (will use follow-up PR for these):
* write concatenated ts segment to disk
* fix/add tests
=> concatenate segments

clients/mediaconvert_test.go, pipeline/coordinator.go, pipeline/coordinator_test.go, video/probe.go, video/profiles.go
Only send to mist if the input codecs are known to be compatible to avoid unnecessary failures
=> Check codecs are compatible with mist

clients/input_copy.go
At the moment we don't get an indication that an error and retry has occurred, so this log line will allow us to clearly see when retries have happened and what the error was each time
=> Add log line for copy attempt failures

video/probe.go, video/probe_test.go, video/profiles.go
This will allow us to continue processing videos where the only issue is a missing bitrate in the probe output
=> Set a default bitrate if we don't find one

clients/input_copy.go, clients/mediaconvert.go, clients/object_store_client.go, transcode/transcode.go, video/profiles.go
The MP4 outputs are now being added to the studio notification for the mist pipeline, so that we can advertise these for playback
=> Populate MP4 outputs in studio notification for mist

clients/input_copy.go, video/probe.go, video/probe_test.go, video/profiles.go
Log input video/audio track info so that we can identify any raciness in the ffprobe behavior to root
cause cases where the input file uses mp4 + aac but still ends up in the
mediaconvert pipeline instead of solely using the mist pipeline.
=> Log input video/audio track info

pipeline/coordinator.go, pipeline/coordinator_test.go, pipeline/external.go, pipeline/mist.go, video/profiles.go
**metrics: add in_fallback_mode metric to track fallbacks**
If the Catalyst pipeline fails for any reason, we want to track every
request-id that ends up falling back to the Mediaconvert pipeline. Add a
metric (in_fallback_mode) to track when a job has fallen back into the
backup pipeline.
**metrics: fix duration/codec metrics to track pipeline state**
A few metrics were not populated in the postgres db depending on the
pipeline used (catalyst vs mediaconvert). Add the missing metrics and
commonize codec metrics between the two pipelines.
=> add + fix pipeline metrics

transcode/transcode.go
When the input video's res/bitrate combo is too low for the default ABR ladder, an additional low-bitrate profile with 50% of input bitrate is generated for ABR HLS based playback. For MP4s, only a single MP4 matching the default ABR is required so skip MP4 output for low bitrate profiles.
=> transcode: skip mp4 output for low-bitrate profiles

handlers/upload.go, handlers/upload_test.go
We've been seeing a lot of these in Production
=> Reject Source URLs with .local domain

pipeline/coordinator.go, pipeline/coordinator_test.go
coordinator: use fb_ prefix for request-id if fallback pipeline is being used
=> fix fallback job primary-key db entry

api/http.go, handlers/playback.go
Removing this as MP4s will still come in via the manifest endpoint which won't work. I am switching to handling manifests and media from a single endpoint in another PR, I'm removing this code in its own PR because it cleans up the diff nicely for the next PR
=> Remove media playback endpoint

clients/object_store_client.go
In a few places we're passing in the full destination URL as the `osURL` param with `filename` blank. This meant the error message made it appear like there was a bug with filename being empty
=> Fix confusing error message

Makefile, scripts/mist-cleanup.sh
This PR integrates the mist-cleanup script that will be called periodically to clean up /dev/shm. A separate PR will be used to actually schedule and call this script. 
Best to review on a per commit basis. @Thulinma: FYI so that you can see the diff from your original script. 
Related Catalyst PR to install the script in `build/` dir: https://github.com/livepeer/catalyst/pull/441
=> add mist cleanup script to catalyst-api

metrics/metrics.go, pipeline/coordinator.go, pipeline/coordinator_test.go
This will allow us to track on our dashboard which jobs are being sent to mediaconvert due to the codecs not being supported by mist
=> Add a metric flag to show whether codecs are mist supported

clients/arweave_ipfs_s3.go, clients/input_copy.go, clients/mediaconvert.go
This is to improve the chances of us being able to download >2GiB files from IPFS.
Moved retryableHttpClient to input_copy.go since it was only used there.
=> Increase copy timeout

.github/workflows/build.yaml
This change will ensure all output from 'make build' in catalyst-api will get copied to the tar balls. Specifically, this change is being done so that the mist-cleanup scripts get installed onto pods which will be called by catalyst-api.
=> build.yaml: tar up everything in build/ dir of catalyst-api

clients/callback_client.go, clients/callback_client_test.go, handlers/handlers_test.go, main.go, transcode/transcode_test.go
Callback client now passes `--api-key` instead of a hardcoded `IAmAuthorized`.
=> clients/callback: send auth key back up

main.go
Depending on how many pages need to be deleted, this process can take several mins upwards of 5mins to complete. Raising this to 15min instead.
=> mist-cleanup: set timeout of script to 15min instead of 5min

handlers/accesscontrol/access-control.go
The gate API is expecting to receive a type field, previously it always had a default value even for public streams so this is just to restore that behaviour
=> Fix access control for live streams

api/http.go, handlers/geolocation/geolocation.go, middleware/cors.go
Simple change but I created a middleware for it so we can re-use it across browser-facing APIs.
=> api: Set CORS headers on gated playback API

pipeline/coordinator.go
Several audio-less video is uploaded to livepeer. These jobs get recorded in the db as having a blank codec field which makes it tricky to parse stats. Explicitly set these job fields to "n/a" whenever a codec is missing for a given video/audio track.
=> metrics: populate undetected audio/video codecs as "n/a"

mapic/mistapiconnector_app.go
In the event of a "banned" account, we want to return an empty string with a 200 rather than a 403 with "false" which Mist considers a failure.
=> mapic: always return 200 from mist trigger

mapic/mistapiconnector_app.go
Haven't checked if there are other configs we're
ignoring, but doing this in a rush so this already fixes the known problem.
=> mapic: Grab SendAudio from config directly

pipeline/coordinator.go, pipeline/coordinator_test.go
We've been seeing issues with Mist's handling of large files so until that's resolved, let's route those to the backup pipelines.
=> Don't use Mist for large files

clients/input_copy.go, clients/input_copy_test.go, pipeline/coordinator.go, pipeline/coordinator_test.go
Direct uploads mean that studio has already copied the input file to object store so there's no need for us to copy to our transfer bucket which will save some moneys
=> Dont copy input file to transfer bucket if its a direct upload

config/config.go, pipeline/coordinator.go, pipeline/coordinator_test.go
We've been seeing a much improved Mist error rate with the latest changes, so going to gradually increase this limit again
=> Bump Mist input file size limit from 200Mb -> 500Mb

config/config.go, pipeline/coordinator_test.go
We haven't seen any issues with it handling the smaller files
=> Bump limit for files we send to Mist from 500Mb to 1Gb

test/cucumber_test.go, test/steps/init.go
We were sometimes getting cucumber test failures as we were trying to hit the mock studio endpoint before it had started up
=> Wait for http servers to start up before continuing cucumber tests

api/http.go, handlers/playback.go, playback/playback.go, test/cucumber_test.go, test/features/playback.feature, test/steps/http.go
Seeking in the player was broken because we weren't signaling that we support range requests. I have added an http HEAD handler for this and implemented a custom OPTIONS handler.
=> Fix MP4 range requests for access control playback

handlers/schemas/UploadVOD.yaml, handlers/upload.go, pipeline/coordinator.go, pipeline/coordinator_test.go
I already added the `external_id` column to both staging (canary) and prod metrics DBs.
Related Linear issue: https://linear.app/livepeer/issue/VID-103/allow-passthrough-of-external-id-to-metrics-database
FYI: @ecmulli
=> Add external_id to VOD upload request

go.mod, go.sum, video/probe.go, video/probe_test.go, video/profiles.go
My go-ffprobe PR has been merged upstream now so updating to the latest here. I included a built in helper for the library so I've removed the one here now.
=> Update to latest ffprobe library

clients/input_copy.go, clients/input_copy_test.go, clients/mediaconvert.go, video/probe.go, video/probe_test.go
Add support for HLS (m3u8) input files in mediaconvert VOD pipline
* HLS input files will be used for backup-recordings - a VOD workflow
will be kicked off with these source input m3u8s which will result in
transcoded renditions of recordings.
* Recordings will be considered as directUploads from a public GCS
bucket
* Probe functions were updated to handle HLS files where bitrate/fps may
not get reported correctly.
=> recordings v2: use hls input sources for mediaconvert pipeline

pipeline/external.go
Mediaconvert needs to return the input video spec, because it's used in the Transcode API to return input video size and duration.
=> Fix mediaconvert not returning video spec

handlers/handlers_test.go, middleware/capacity_test.go, pipeline/coordinator.go, pipeline/coordinator_test.go
Once we get this onto Staging, it will mean the FFMPEG become the default first pipeline and we can begin testing in earnest.
Still TODO in future PRs: 
- Check if there are any pipeline-specific metrics we want to add
- Check for callbacks in integration tests
=> Switch 'fallback' strategy to FFMPEG->External

pipeline/coordinator.go
The new pipeline was getting grouped under "mist" in metrics because of this
=> Record the correct pipeline name

api/http.go, metrics/metrics.go, middleware/logging.go, test/cucumber_test.go, test/features/playback.feature, test/features/vod.feature, test/steps/http.go
So we can monitor access control usage and the quality of the service (error rates and response times).
=> Add request metrics for playback requests

go.mod, go.sum, handlers/playback.go, pipeline/coordinator_test.go, playback/playback.go
In order for MP4 playback to work in safari it needs the content-range header to be returned.
I've tested this on chrome, safari, firefox and edge (macos). It's taking longer than hoped to write a cucumber test for this so I'm going to do a follow up PR.
=> Fix range requests on safari

config/config.go, metrics/metrics.go, pipeline/coordinator.go, pipeline/coordinator_test.go
There's no reason the FFMPEG pipeline shouldn't be able to handle file sizes up to our maximum, so remove the limit and update logs etc. to refer to the Livepeer pipeline rather than Mist.
=> Remove size limit from FFMPEG pipeline

pipeline/ffmpeg.go, pipeline/mist.go
Fortunately this value wasn't used for anything affecting end users but we have been reporting incorrect source segment counts for a long time. The m3u8 library pre-allocates space in its segments slice so we were seeing values of `1024` for the vast majority of jobs. Using the `GetAllSegments()` helper function fixes this issue and gets you the true value.
Example from prod `vod_completed` table:
```
request_id | source_segment_count | transcoded_segment_count
------------+----------------------+--------------------------
gahabehh   |                 1024 |                        2
```
=> Fix segment counts reported

video/segment.go
Doing the `copy` without specifying streams gives: 
```[webvtt @ 0x13b607360] Exactly one WebVTT stream is needed.
Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
Error initializing output stream 0:2 -- 
```
for the following file:
```
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '1681744560323.mp4':
Metadata:
major_brand     : isom
minor_version   : 512
compatible_brands: isomiso2avc1mp41
encoder         : Lavf58.76.100
Duration: 02:20:36.76, start: 0.000000, bitrate: 456 kb/s
Stream #0:0[0x1](und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(progressive), 1280x720, 322 kb/s, 25 fps, 25 tbr, 12800 tbn (default)
Metadata:
handler_name    : VideoHandler
vendor_id       : [0][0][0][0]
Stream #0:1[0x2](und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 …
```
=> Don't fall over when subtitles track is present

Makefile
Needed for a working `make` on first run.
=> Makefile: install golangci-lint and godog

pipeline/coordinator.go, pipeline/coordinator_test.go, pipeline/ffmpeg.go
This was causing issues when the foreground pipeline failed but we continued trying to send callbacks
=> Remove fb_ prefix from Request ID when falling back

pipeline/ffmpeg.go, video/segment.go
This was due to observed issues where FFMPEG would become very slow to segment and make large numbers of range requests per segment when segmenting remote files.
We now download the file to a local temp directory (with a deferred step to remove it afterwards) before segmenting.
=> Pull down source file locally before segmenting

pipeline/ffmpeg.go, transcode/manifest.go, transcode/manifest_test.go, transcode/transcode.go, transcode/transcode_test.go
We need to do this to verify the segments are not corrupt in any way. We found with one input video this was happening (playbackID 97b1rnzi74ps1g58)
=> Probe segments coming out of the ffmpeg segmenting process

clients/callback_client.go, clients/callback_client_status.go, clients/callback_client_test.go, config/timestamp.go
Previously we were comparing seconds to milliseconds so stale callback messages were essentially never timing out with this check. I've fixed the check by switching to `time.Time` types to make it clearer.
=> Fix callback stale check

config/cli.go, main.go, mapic/mistapiconnector_app.go, mapic/misttriggers/stream_buffer.go, mapic/misttriggers/stream_buffer_test.go
Basically works by parsing the Mist STREAM_BUFFER payload into a single
JSON object and pushing it to a "stream heath hook url" configured on cli.
The Studio API will handle updating the stream health with what comes in
that trigger (e.g. can easily start handling the END trigger soon).
This was meant to be catalyst-api code, but in the midst of the implementation
I realized it has no connection with Mist anymore, so it's easier to plug this into 
mist-api-connector instead for now (especially due to code/config familiarity).
Nice that it's all in the same repo which makes it easier. I also implemented it
in a way that makes sense for catalyst-api (no hard deps on Studio API) so
it's easy to migrate in the future.
=> mapic: Add STREAM_BUFFER handling for stream health reporting

video/probe.go, video/probe_test.go
Before this, we were inconsistent between ffmpeg 4 and 6:
```
ffprobe version 6.0 Copyright (c) 2007-2023 the FFmpeg developers
Duration: 00:00:16.21, start: 0.000000, bitrate: 1372 kb/s
ffprobe version 4.2.7-0ubuntu0.1 Copyright (c) 2007-2022 the FFmpeg developers
Duration: 00:00:16.25, start: 0.000000, bitrate: 1368 kb/s
```
By looking at the video track directly, we sidestep the issue. Except that fails for the VP9 sample for whatever reason:
```
--- FAIL: TestProbe_VP9 (0.07s)
probe_test.go:122:
Error Trace:	/Users/iameli/code/catalyst-api/video/probe_test.go:122
Error:      	Received unexpected error:
error parsing videoStream.Duration: strconv.ParseFloat: parsing "": invalid syntax
Test:       	TestProbe_VP9
FAIL
FAIL	github.com/livepeer/catalyst-api/video	3.177s
FAIL
```
So I added …
=> video: check video track for duration first

mapic/misttriggers/stream_buffer.go
Let's avoid a bunch of errors when we just haven't configured it.
=> mapic/triggers: Make sure stream health URL is present

mapic/misttriggers/stream_buffer.go, mapic/misttriggers/stream_buffer_test.go
Turns out that the Mist docs I used were outdated. Instead of having only the `issues` field
additional on that JSON, we actually have some other int/float metrics that need to be removed
as well so we can parse the rest as track objects. 
Updated the code with the assumption now that any object field is a track, and the rest are
either issues or "extra" fields we don't really care. Still include those in a separate `extra`
object for logging on the API.
For ctx, this is the error the code is getting now: `error parsing stream details tracks: json: cannot unmarshal number into Go value of type misttriggers.TrackDetails`
Which happens because we fields like this in the root object of the payload:
```
"buffer": 34667,
"jitter": 51,
"maxkeepaway": 7500,
```
Also found out that, when issues …
=> mapic: FIx stream_buffer payload parsing

mapic/misttriggers/stream_buffer.go, mapic/misttriggers/stream_buffer_test.go
It is undocumented and I assumed it was a string just like the issues. Turns out it is a string array.
If I just changed the types it would make the parsing logic much more convoluted, as the array is actually parsed as a []interface{} and I'd need to check each item. So I changed it once again, making yet another parsing of the input object.
=> mapic: Fix parsing of human_issues field

video/probe.go
We've been getting a lot of these recently and should reject before trying to send them for transcoding
=> Reject PNG video tracks without trying to transcode

clients/callback_client.go, clients/callback_client_status.go, clients/callback_client_test.go, config/timestamp.go
Reverts livepeer/catalyst-api#623
We saw errors with task-runner parsing time.Time instead of timestamps
=> Revert "Fix callback stale check"

clients/callback_client.go, clients/callback_client_test.go, pipeline/coordinator.go, pipeline/coordinator_test.go, transcode/transcode_test.go
Send final callbacks (status: `TranscodeStatusError` and `TranscodeStatusCompleted`) in a sync manner and wait until the result. If sending the callback fails, then set the status of the job to `failed`.
It prevents the situation in which:
1. Catalyst successfully completed its job
2. It failed on sending the callback to task-runner
3. In studio we see the job as `failed`
4. In Catalyst metrics DB we see the job as `completed`
Note that from now on the opposite situation will be possible, so recording the job as `failed` in metrics DB and having task `complated` in task-runner.
=> Fail job if sending the final callback fails

clients/arweave_ipfs_s3.go, clients/arweave_ipfs_s3_test.go, clients/input_copy.go, clients/manifest.go
Previously different gateways were only used when the request to the gateway simply failed, not for the case when we fail to read data from it.
Example log showing the same gateway `vod-import-gtw.mypinata.cloud` being used when read EOFs occur:
```
2023-04-04 15:45:42.115	
[2023-04-04 15:45:42] livepeer-catalyst-api (3749675) INFO: ts=2023-04-04T15:45:42.11471537Z request_id=fcgbfdbh source=ipfs://bafybeihztylfsfn4ezyz753r5t4qdd2g67auynut2ciai6ll57l6spka3a target_segment_size_secs=10 msg="Copy attempt failed" source=ipfs://bafybeihztylfsfn4ezyz753r5t4qdd2g67auynut2ciai6ll57l6spka3a dest=s3+https:/GOOG1EKMFSJCOIK6YM7FDZBYKZ2COZDX6MYQBT4PC6LF2SHARA3WO55EHHPPY:xxxx@storage.googleapis.com/lp-us-catalyst-vod-com/hls/source/fcgbfdbh/transfer err="failed to write to OS URL …
```
=> Retry through different Dstorage gateways when download failures occur

balancer/balancer.go, balancer/balancer_test.go, main.go
Originally we were going to not pass the local node to the balancer entirely — we don't want that, because it means Catalyst nodes would never under any circumstances send people to watch a stream on themselves. Single-node clusters wouldn't work at all. Instead, the trick will be to rewrite our own node URL to 127.0.0.1 on the way in and out of the Mist load balancer. MistUtilLoad is already smart enough to ignore source requests coming from the same IP address: https://github.com/DDVTECH/mistserver/blob/6393a5a4cdc86667351f12f93b1e3cd22477a144/src/utils/util_load.cpp#L635-L638 so that will result in source (replication) requests never routing to the local node while playback requests can still do so.
=> balancer: rewrite local node to 127.0.0.1 in MistUtilLoad

balancer/balancer.go, balancer/balancer_stub.go, balancer/balancer_test.go, handlers/geolocation/geolocation.go
Refactors balancer to use MistUtilLoad's `streamstats` query parameter to determine whether a stream is live anywhere. https://github.com/livepeer/catalyst-api/pull/670 introduced a problem — we successfully avoid balancing to the local node to avoid redirection loops but that also means we broke "stream is live" detection for the local node.
Also includes more tests and some refactoring of the MistUtilLoad calls to make much clearer what's happening; the primary balancing calls are now split off into their own functions with this signature:
```
MistUtilLoadBalance(ctx context.Context, stream, lat, lon string) (string, error)
MistUtilLoadSource(ctx context.Context, stream, lat, lon string) (string, error)
MistUtilLoadStreamStats(ctx context.Context, stream string) error
```
=> balancer: use streamstats to determine if a stream is live

balancer/balancer.go
This is just an `errgroup` fail on my end — I thought _any_ function returning would cause the cancellation of the errgroup context, not just a non-nil error response. This caused situations where MistUtilLoad failed to start but we never found out about it. Changed to ensure an error is always returned.
=> balancer: crash if MistUtilLoad exits

config/stream_names.go, config/stream_names_test.go, transcode/transcode.go
We previously were only using the first X characters from our charset (where X is the length of the requested random string) and were also reinitialising the random generator on each request.
=> More random stream names

transcode/transcode.go, transcode/transcode_test.go
The last segment in an HLS manifest may contain an audio-only track - this is common during a livestream recording where the video stream can end sooner with a trailing audio stream which results in a segment at the end that just contains audio. This segment should *not* be submitted to the T.
TODO: 
* need to add a unit test for this
* verify recordings without this last-segment-is-audio-only-track issue still works as expected.
=> transcode: drop last segment in HLS manifest a video track is missing

clients/callback_client_status.go
I'm adding this field on its own initially so that I can update task-runner with it too before using it, thus avoiding any json parse issues
=> Add field to notfiy task runner about source playback

mapic/mistapiconnector_app.go
https://linear.app/livepeer/issue/VID-49/catalyst-api-return-200s-for-push-rewrite-triggers
=> Return 200s for push rewrite trigger if stream is deleted or not found

clients/callback_client.go, clients/callback_client_status.go, clients/object_store_client.go, go.mod, go.sum, pipeline/ffmpeg.go, pipeline/ffmpeg_test.go, test/cucumber_test.go, test/features/vod.feature, test/steps/broadcaster.go
To improve our time to ready we are implementing source playback. We write a master playlist pointing at the segmented source playlist and notify task-runner this is available (which in turn notifies studio). When transcoding is complete this master playlist is overwritten with the final transcoded version.
=> Source playback

api/http_internal.go, clients/mist_client.go, clients/mist_client_mock.go, clients/mist_client_test.go, handlers/misttriggers/push_end.go, handlers/misttriggers/push_end_test.go, handlers/misttriggers/push_out_start.go, handlers/misttriggers/stream_buffer.go, handlers/misttriggers/stream_buffer_test.go, handlers/misttriggers/triggers.go, mapic/mistapiconnector_app.go
Needed for multistreaming improvements and other planned integrations with Mist. Brings back the PUSH_OUT_START and PUSH_END triggers, and moves the STREAM_BUFFER trigger over to the `handlers/misttriggers` folder where it's needed.
I originally did a more comprehensive refactor where `streamHealthClient` became its own thing in the `clients` directory but got stuck on a circular dependency; streamHealthClient needed to know about `misttriggers.StreamHealthPayload` and the stream buffer handler needed to know about the `streamHealthClient`. I still thing a refactor along those lines is more better, but this is an incremental improvement in the meantime.
=> re-add handlers/misttriggers

clients/input_copy.go, clients/manifest.go, clients/object_store_client.go, transcode/transcode.go
We want to pass the plain HTTP input URL through for recordings because this is the simplest way to allow mediaconvert to read the input (in case of livepeer pipeline failures). Some parts of the code were expecting an OS URL though so this is what is fixed in this PR, to allow plain HTTP URLs to work too.
=> Fix recordings

clients/input_copy.go, clients/input_copy_test.go
We need to go back to copying the recording manifest and segments to the playback bucket to allow source playback to work, the playback urls are pointed at this bucket not the recordings one.
To get around the issue we had with mediaconvert reading a signed hls input url (appending the signing queryparams to the segment urls) I am now only generating a signed url when the unsigned version is not accessible.
=> Fix recordings source playback

api/http_internal.go, handlers/misttriggers/broker.go, handlers/misttriggers/push_end.go, handlers/misttriggers/push_out_start.go, handlers/misttriggers/stream_buffer.go, handlers/misttriggers/stream_buffer_test.go, handlers/misttriggers/trigger_broker.go, handlers/misttriggers/trigger_broker_test.go, handlers/misttriggers/triggers.go, main.go, mapic/mistapiconnector_app.go, mapic/start_mapic.go, middleware/logging.go
Adds a `Broker` interface responsible for dispatching Mist events to other parts of the code. If some part (like mapic) needs to handle an event, it can be passed the Broker on initialization and use it something like [this](https://github.com/livepeer/catalyst-api/pull/737/files#diff-07d76f8f8ce6678348918ef729dbe84cf0bea01df42fc4c84e0c2aabf8dd8ce4R142).
Also a bonus commit to once again fix the `reject()` logic for webhooks! I swear I had tested and had it working but apparently not.
=> [VID-258][VID-4] remove CONN_CLOSE

clients/input_copy.go, clients/input_copy_test.go, handlers/upload.go, pipeline/coordinator.go, pipeline/coordinator_test.go, test/cucumber_test.go, test/features/vod.feature, test/steps/broadcaster.go, test/steps/http.go, test/steps/upload_request.go, transcode/transcode.go, video/probe.go, video/probe_test.go, video/profiles.go
- Moved a few lines of code that decide the copy destination out of `clients/input_copy.go` and into `pipeline/coordinator.go` to be able to reference the `SourceCopy` flag on the job object. If the flag is set we will now copy the source file to the `video` location which task-runner and studio expect.
- Set some missing probe fields so that we can then remove the probing from task-runner
=> Single download pipeline - implement request param to make a source file copy

.github/workflows/build.yaml, clients/manifest.go, clients/manifest_test.go
This takes the clients testing from ~105s to ~7s
=> clients: bypass backoff/retry for testing

clients/broadcaster_local.go, config/cli.go, main.go, pipeline/coordinator.go, pipeline/ffmpeg.go, test/cucumber_test.go, test/features/playback.feature, test/features/vod.feature, transcode/transcode.go, transcode/transcode_test.go
The integration tests were making use of ports 3000, 7979, 8989, and 8935. This obviously needs to port conflicts if you try and run `make integration-test` while running a node locally, which is a shame.
I thought it would be a small change, but it turns out making the local broadcaster URL configurable is a little bit larger - needed to update the flow of how that URL and clients are passed down. Not very familiar with those parts of the code, let me know if there's a better way to do it
=> test: avoid port collisions

pipeline/coordinator.go, pipeline/coordinator_test.go
This fixes the check to account for negative differences. I should have added the customer example into the unit tests the first time around
=> Fix display aspect ratio check

pipeline/coordinator.go
We'd swapped from using a different Request ID across primary / fallback becuase of issues with cleaning up the job cache, but this meant we started hitting unique key conflicts when writing the status of the fallback job to Postgres.
=> Don't fail to write postgres metrics in fallback pipeline

clients/mist_client.go, clients/mist_client_test.go
So the bug that we had was actually here
https://github.com/livepeer/catalyst-api/blob/7e08a7d4df0af33c7e371e5f28745571903caa31/clients/mist_client.go#L243
That line was a lie. It wasn't an `application/json` body, it was an `application/x-www-form-urlencoded` body.
But JSON is easier to work with anyway, so @Thulinma [implemented support for JSON bodies on these API calls](https://github.com/livepeer/mistserver/commit/1967f52bfa18e0504e506531760c42e1394be1e6) and this PR switches us to making JSON calls. This needs to roll out at the same time as livepeer/mistserver@1967f52bfa18e0504e506531760c42e1394be1e6.
=> clients/mist: speak json to the mist api

clients/input_copy.go, handlers/upload.go, pipeline/coordinator.go, pipeline/ffmpeg.go, pipeline/ffmpeg_test.go, video/probe.go, video/probe_test.go, video/profiles_test.go
- We found another case of bad (non-existing PPS 0 referenced) segments so we need to expand the checks to more segments https://linear.app/livepeer/issue/VID-270
- I found that we were ignoring the pps 0 error so I've refactored that to only apply to input videos, since the intention there was to ignore mist recording probe errors
- Included the fix for the other segmenting issue that has been found (audio corruption) https://linear.app/livepeer/issue/VID-287
=> Probe more segments after segmenting

clients/mist_client.go, clients/mist_client_test.go
This ensures a smooth rollout of https://github.com/livepeer/catalyst-api/pull/764
=> TEMP BRANCH: use application/x-www-form-urlencoded

config/cli.go, main.go, scripts/pod-mon.sh
`pod-mon` (aka pod-monitor) is used to log all system level metrics. This script is called periodically via catalyst-api so that resource usage is logged "in-line" with catalyst-api logs. This should make debug usage issues in relation to what catalyst-api is currently doing.
#\Fix VID-293
=> pod-mon: add script to monitor system usage in-line with catalyst-api

clients/manifest.go, clients/manifest_test.go
HLS players begin playing a stream by typically loading the first rendition listed in a master playlist. The player will attempt downloading a few segments from the first rendition before playback can begin. For 4K resolutions, the segments can be fairly large in size (~20MB in some cases) and this results in a very slow TTFF. In order to optimize quick playback, we prioritize a rendition lower than 4K and then let the HLS player adjust quality as playback continues -- this ensures TTFF are short and the viewer sees playback begin quickly.
Fix VID-222
=> clients: update manifest ordering logic to handle 4K resolutions

clients/manifest.go, clients/manifest_test.go
It was found that 2k segments can also be ~60MB in size resulting in
long download times for the first segment and thus long TTFFs. So change
the threshold for ABR ordering to 2k instead of 4k previously.
=> manifest: update ABR ordering logic to optimize playback for 2k and greater resolutions

pipeline/coordinator.go, pipeline/coordinator_test.go
We're initially going to check if the transcode pipeline already handles doing the audio transcode to AAC and if not, start doing that transcode inside Catalyst API
=> Stop falling back based on audio codec

pipeline/coordinator.go, pipeline/coordinator_test.go
Reverts livepeer/catalyst-api#796
=> Revert "Stop falling back based on audio codec"

handlers/upload.go, handlers/upload_test.go, pipeline/coordinator.go, pipeline/coordinator_test.go, pipeline/ffmpeg.go, transcode/transcode.go, video/transmux.go
This PR adds the option to generate fragmented-mp4s packaged with HLS. 
**TODOs:**
~~* Add option to generate different mp4 types in vod request handler~~
~~* Fix location of output dir for fmp4 in object-store~~
~~* Fix mp4 output response to Studio~~
~~-- Fix probing issue post-transcode~~
~~-- Fix fmp4 output to generate separate a/v tracks~~ --> will be a followup PR
~~-- Fix/add unit tests~~ (separate PR will be used for integration tests)
~~-- Some more testing in staging including regression testing~~
/Fix VID-341
=> Add support new output format (fragmented-MP4 packaged with HLS)

video/transmux.go
We were seeing transmuxes sometimes fail to detect the video codec and so produce audio-only results.
=> Add analyzeduration param to stop transmux failures

clients/mediaconvert.go, handlers/schemas/UploadVOD.yaml, handlers/upload.go, handlers/upload_test.go, transcode/transcode.go, video/profiles.go, video/profiles_test.go
The transcode profile logic is being updated to handle these new changes:
* The transcode-api will now pass through empty profiles to catalyst-api. These cases should use catalyst-api's default ABR ladder.
* The transcode-api will also allow profiles with just the bitrate field set. These cases should use the resolution of the input video with the specified target bitrate for transcoding.
TODO: add/fix tests
=> profiles: support transcode for empty profiles and bitrate-only profiles

video/probe.go, video/probe_test.go
I'm correcting some differences I saw to task-runners probing logic so that we can use catalyst's output and remove the logic from task-runner
=> Add track durations to match task-runner

clients/manifest.go, clients/manifest_test.go, transcode/transcode.go, video/profiles.go, video/transmux.go
- Only probe mp4 and fmp4s media files after they are generated i.e.
skip any manifest files for fmp4s since probing takes a while and
sometimes returns errors.
- Add fmp4 master playlist as an addition output video in the final
response to Studio.
=> manifest: update output video list with fmp4 manifest urls

clients/input_copy.go, config/cli.go, main.go, pipeline/coordinator.go, pipeline/ffmpeg.go, pipeline/ffmpeg_test.go, test/steps/broadcaster.go
This is to drastically speed up processing for recordings. A new config param was needed to allow source playback still to work, this is so that app knows what hostname to use in the source playback manifest (to reach the recordings bucket rather than the normal asset bucket). E.g. a source playback manifest for a recording will look something like:
```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-STREAM-INF:PROGRAM-ID=0,BANDWIDTH=4000000,RESOLUTION=1280x720,NAME="720p"
//recordings-cdn.lp-playback.studio/hls/b7caqhzl06ma2iqn/e0e9a30f-769c-4e50-9b69-2cf0ac97e68c/output.m3u8
```
=> Skip source copy for HLS input

config/cli.go, handlers/geolocation/gelocation_test.go, handlers/geolocation/geolocation.go, main.go, metrics/metrics.go
https://linear.app/livepeer/issue/SRE-160/cdn-big-red-button
catalyst-api to support new `-cdn-redirect-playback-ids` and `-cdn-redirect-prefix` parameters.
This implementation requires changes to `catalyst-api` helm values and `catalyst` deployment.,
In future the list of CDN-redirected playbacks could be pulled from studio...
=> [SRE-160] CDN redirect

mapic/mistapiconnector_app.go, mapic/mistapiconnector_app_test.go, mapic/stats_collector.go
Reverts livepeer/catalyst-api#819
Reverting until we're confident enough to deploy this
=> Revert "fix: active idle status & restore metrics collection"

clients/input_copy.go, video/clip.go, video/clip_test.go
For some HLS streams, the duration cannot be detected correctly and
ffprobe reports "N/A" as duration. This was evident in long running
livestreams that were 100s of hours in length. In such cases, we parse
the manifest file using the m3u library to manually determine the
duration by adding up segment lengths as reported by the EXTINF tags.
=> Manually parse duration for HLS manifests where ffprobe can't determine duration

handlers/schemas/UploadVOD.yaml, handlers/upload.go, pipeline/coordinator.go, video/clip.go
This adds additional parameters to the vod endpoint to accept clipping start/end times. If the fields are set with valid values, the input manifest will be clipped and then a new clipped manifest will be used in the VOD pipeline to generate assets as usual. The logic for clipping the actual manifest will be done as a follow-on PR.
=> clip: add scaffolding to accept clipping requests

pipeline/ffmpeg.go, pipeline/ffmpeg_test.go
The hostname in the storj urls is not unique so had to switch this logic to a string substitution. I've confirmed this is working on staging.
=> Enable source playback for storj recordings

video/probe.go
We were pulling the wrong field from the stream
=> Fix 'duration' field for audio-only assets

handlers/schemas/UploadVOD.yaml, pipeline/coordinator.go, video/clip.go
This playback-id will be returned in the clipping response back to studio so that clipped assets can be tracked to the original asset's playback id.
=> handlers: add playback-id to clipping request

clients/manifest.go, handlers/upload.go, pipeline/coordinator.go, video/clip.go
Add manifest handling logic to download a source manifest, call clipping methods on it, and then upload the returned segments to OS.
Note 1: The clipped manifest generation and upload step will be done in a follow-on PR.
Note 2: cucumber tests will be added in a future PR
=> clip: add support to clip and upload clipped segments

clients/manifest.go, video/clip.go
The player is able to send absolute unix timestamps when setting the start/end times of the clips. So we switch to accepting unix timestamps in milliseconds and then convert it to offsets in seconds.
TODO: need to add a test.
=> clip: switch start/end time in request to unix timestamps in milliseconds

config/config.go, test/features/vod.feature, transcode/transcode_jobs.go
This is an attempt to mitigate the number of first segment swaps we see, based on the issue described in https://github.com/livepeer/go-livepeer/pull/2860
=> Stagger transcode goroutines to avoid switching Os

video/clip.go
The -ss and -to parameters used by ffmpeg was previously only converting to HH:MM:SS and the milliseconds portion was being dropped. Update the time formatting logic so that a format of HH:MM:SS.m... is used. This allows millisecond accuracy for clipping.
=> clip: format start/end times passed to ffmpeg to use milliseconds

handlers/schemas/UploadVOD.yaml
The clipping request is already validated in catalyst-api so we should not be setting start_time in the vod request as this will prevent recordings/vod from working.
=> UploadVOD yaml: do not set start_time as required

clients/manifest.go
This is a bit of a workaround (hack) to correctly set storj URLs for the clipped manifest file. A follow-on PR will be used to set the output relative path in the request directly which will will simplify this logic.
=> manifest: set the clipped manifest URL correctly for storj

clients/manifest.go, clients/manifest_test.go, video/clip.go
If the last segment is not re-encoded, some hls players take additional audio from the last segment and overlap with the beginning of the video - the symptom is that you hear mismatched audio track. This doesn't always reproduce on the same hls player at times when reloading multiple times.
Re-encoding the last segment and adding a DISCONTINUITY tag seems to resolve the issue here as well.
=> manifest/clip: re-encode last segment as well and add DISCONTINUITY tag

clients/manifest.go, pipeline/coordinator.go, video/clip.go
**coordinator: add retries to clipping**
* In several cases, we may attempt clipping segments that have been
partially written to storage. In this case, ffmpeg/ffprobe operations
will fail and we should retry a bit before giving up.
**clip: add map arguments to ffmpeg clip commands**
* The clip segments that are re-encoded will end up with the video track
first and audio track second wheras the track ordering is reversed for
the source recorded segments. If these segments are transmuxed into a
single ts/mp4 file, the resulting file will stop playing after the first
segment's worth of video. To resolve this, this commit adds the 'map'
args to the ffmpeg command to ensure the audio track is always placed
first and video track second similar to the recorded segments.
* The ffmpeg call is …
=> clipping fixes

pipeline/ffmpeg.go
While testing locally I noticed that this line was panic'ing on `localSourceFile.Name()`
=> Fix nil panic

clients/broadcaster.go, clients/broadcaster_local.go, pipeline/ffmpeg.go, transcode/transcode.go, transcode/transcode_test.go
When a sequence of segments has a discontinuity (e.g. encoded differently), the transcoder at T must be re-initialized so that transcode operations can be completed correctly. The T takes some liberties and assumes a sequence of segments are encoded the same way and thus, ends up not re-initializing certain parts of the pipeline (e.g. demuxer, etc) to save time and improve efficiency. This can result in corrupted segments with two video tracks instead of one audio and one video track.
For clipping, the first segment (index=0) is encoded differently from the rest of the file. As such, a session reinit must be forced at the T using a header set in the request to B.
=> transcode: add logic to force a session re-init

clients/manifest.go, clients/manifest_test.go, transcode/transcode.go
A discontinuity tag is required in the clip playlist so that it shows the correct duration.
=> manifest: add DISCONTINUITY tags to clip playlist

handlers/misttriggers/user_end.go
This is to help us debug discepancies between what we're reporting via this method vs access logs
=> Log body of USER_END trigger

pipeline/ffmpeg.go
In the transcode-api, an hls target may not be set in which case source playback doesn't apply.
=> transcode-api: disable source playback if hls target url is not set

transcode/transcode.go, transcode/transcode_jobs.go, transcode/transcode_test.go
~~TODO: need to test directly in Staging before merging.~~
=> transcode: apply T re-init logic for last clipped segment

api/http_internal.go, handlers/ffmpeg/ffmpeg.go, test/steps/ffmpeg.go, video/segment.go
This is to fix the case where the source has two keyframes very close together resulting in a tiny segment. The ffmpeg format `hls` that we were using unfortunately has no minimum segment duration option and just splits on every keyframe. So I've switched to `segment` which does allow you to set a minimum segment duration.
=> Fix short segment length

pipeline/coordinator.go
Previously we were swallowing the error when going to a fallback pipeline
=> Always log at top level when pipeline errors

config/config.go, test/features/vod.feature
This was after observing initial segments taking > 5s and still triggering the issue
=> Increase wait before parallel transcoding begins, to account for longer transcode times

pipeline/ffmpeg.go
Some input videos may not follow the h264 spec exactly - ffprobe/ffmpeg may throw warnings on such input but the videos can be decoded and played by all players. For these specific errors/warnings, we can ignore them but we also want to log other types of errors to keep track of all the different possible errors. See VID-450 for more details.
=> ffmpeg: ignore SPS warnings when probing segments

clients/fixtures/mediaconvert_payloads/accelerated.txt, clients/fixtures/mediaconvert_payloads/happy.txt, clients/fixtures/mediaconvert_payloads/no-mp4.txt, clients/mediaconvert.go
Fix VID-461, based on suggestion in https://stackoverflow.com/questions/54527221/aws-mediaconvert-on-media-that-has-no-audio
=> mediaconvert: allow video without audio tracks to be processed

go.mod, go.sum, mapic/stats_collector.go
Fix https://linear.app/livepeer/issue/PS-91/switchboard-idlepending-status-inaccurate
Fix https://linear.app/livepeer/issue/VID-456/recording-stuck-in-progress
Fix https://linear.app/livepeer/issue/PS-84/livespace-webhooks-spamming
It fixes the issue that a stream is Idle (`"isActive": true,`) after finishing streaming for 90s.
**Explanation**
1. In https://github.com/livepeer/catalyst-api/pull/842 we started a loop in which every `1 min` we collect metrics from Mist and then call `setActive(true)` on studio.
2. That can lead to the race condition between this `setActive(true)` and `setActive(false)` sent from `STREAM_BUFFER` trigger when the stream is stopped
3. The root cause is that at the time of sending `setActive(true)` from the metrics collector, we're actually not sure that the …
=> Fix Idle Stream Issue

middleware/cors.go
Allow credentials must be `true` to allow cookies to be passed in the `m3u8` request. 
Also, the allow origin header cannot be a wildcard
=> cors: allow credentials and remove wildcard to allow cookie access key

mapic/mistapiconnector_app.go
This should fix the idle stream issue in the scenario when the stream is started and suddenly stopped.
=> Move setActive(true) from the trigger 'PUSH_REWRITE' to 'STREAM_BUFFER'

pipeline/coordinator.go, pipeline/ffmpeg.go, thumbnails/thumbnails.go, thumbnails/thumbnails_test.go
I had to pretty much rewrite the thumbnail generation so the diff probably isn't that useful when reviewing sorry..
- The old code was reading the input file directly, I realised that wouldn't work for HLS input so it now processes the manifest (after segmenting for mp4 input)
- The old code had quite a complex way to work out the timestamps by parsing the PTS values from the filenames, fortunately that's way simpler now that we just loop through the manifest and get the timings based on the segment durations.
- Now that we're just using ffmpeg to fetch the starting frame of a segment the command is exactly the same as the one we use in catalyst-uploader for the live `latest.jpg`
=> Fix VTT thumbnails

clients/mist_client_test.go, config/cli.go, main.go, mapic/mistapiconnector_app.go, mapic/mistapiconnector_app_test.go
We no longer send audio to MistProcLivepeer ever and we record every stream so we can finally ditch `videorec` and go with `video` every time. Hooray!
=> mapic: remove videorec

transcode/transcode.go, video/transmux.go, video/transmux_test.go
Occasionally, the mp4s of very short clips might stutter as it crosses segment boundaries. This was caused by incorrect PTS between segments which in turn is a result of us clipping and re-encoding the first and last segments "locally". Using a stream based concatenation instead of file based concatenation readjusts the timestamps and prevents these issues.
Note: Eventually, all mp4s will be generated using stream based concatenation if this works well for clipping.
=> transmux: use stream based concatenation for clips

handlers/misttriggers/user_new.go
This change finally make access keys and JWTs working as headers
Now that mist accepts `Livepeer-Access-Key` and `Livepeer-Jwt` as headers (https://github.com/livepeer/mistserver/commit/2e74b3cab6d95f3ed4f4e43b2aa208e54a52c5ba), catalyst-api is able to fetch them from the cookies.
Related docs https://github.com/livepeer/docs/pull/471
=> access-control: make access key as header work

transcode/transcode.go, video/media.go, video/transmux.go, video/transmux_test.go
Transcoded segments are held in memory until the MP4 generation stage (after transcode stage is completed). This results in large usage in RAM when processing very long recordings that are several hours in length. This can occasionally result in kube pods hitting OOM.
To optimize this behavior, this PR makes the following changes:
* Create a buffered channel that holds transcoded segments
* Launch a disk-writing goroutine that consumes the buffered channel and writes segments to disk.
* Delete the byte array of the segment's data in hopes the garbage collector releases it from memory.
* Switch all MP4 generation to use stream-based concatenation instead of file-based concatenation.
=> transcode: memory usage optimization

main.go
https://github.com/livepeer/catalyst-api/blob/main/config/cli.go#L302-L303
> // MistController has trouble giving us `-boolean-flag=false` values, so we use `-no-boolean-flag=true` instead 🤷‍♂️
=> -no-cdn-redirect-prefix-catalyst-subdomain flag (inverted)

clients/input_copy.go
This is not working quite as expected and causing unnecessary failures. Reverting for now
=> Revert "clients: ignore SPS errors when probing input files (#1006)"

handlers/misttriggers/user_new.go, handlers/misttriggers/user_new_test.go
This reverts commit 2a04b39368746a497b621a9c90b02ffcd485f9fd. Seemed to be causing catalyst e2e failures
=> Revert "access-control: return 200 false on triggerUserNew fail (#1014)"

handlers/analytics/user_end.go, test/cucumber_test.go, test/features/triggers.feature, test/steps/database.go
So that if it's slow we don't block responding to Mist's USER_END.
=> analytics: write to database nonblocking

handlers/accesscontrol/access-control.go
Sending the JWT as well with the gate request, to allow studio to suspend keys
=> access-control: send jwt in gate request

handlers/accesscontrol/access-control.go
Fixes https://github.com/livepeer/catalyst-api/pull/1048#discussion_r1431910746
=> access-control: Avoid fail open when JWT is blocked

handlers/accesscontrol/access-control.go, log/clog.go, log/clog_test.go, log/logger.go
Turns out I made _several_ mistakes putting this together! Whoops. Here's a new version with 100% test coverage and also I added a "caller" field so we can see the file stuff came from. Here's an example of a new log message!
```
ts=2023-12-21T22:24:08.87999834Z request_id=MistTrigger-hmhkyeyu msg="Received Mist Trigger" request_id=MistTrigger-hmhkyeyu trigger_name=PUSH_OUT_START mist_version=c111e8bf474a12434548c6b2d94d99dd00e67bdf payload="video+4444444444444444\ns3+http://admin:xxxxx@localhost:9000/os-recordings/$wildcard/$uuid/source/$segmentCounter.ts?m3u8=../output.m3u8&split=5&video=source&audio=AAC&append=1&waittrackcount=2&recstart=-1" caller=triggers.go:58
```
=> log: fix bugs, add "caller" logging, add 100% test coverage

clients/input_copy.go, transcode/transcode.go
When probing, we should ignore SPS errors as they indicate a slightly out-of-spec H264 stream. These files can
still be transcoded successfully so we should be less stringent here.
=> ignore SPS errors when probing

transcode/transcode.go, video/transmux.go, video/transmux_test.go
Generate MP4s only for the first 6hrs. Any input (e.g. recordings) that are longer will still get transcoded up to it's full duration but MP4s will be available for only the first 6hrs.
=> transcode/transmux: set MP4 generation limit

main.go
We should not produce 250 logs/second globally... that'd be killing loki no matter the loki instances size/number.
https://eu-metrics-monitoring.livepeer.live/grafana/goto/T6x1bIKSg?orgId=1
[Discord](https://discord.com/channels/423160867534929930/1189485474121793586)
=> serf messages - loglevel adjustments

middleware/logging.go
https://eu-metrics-monitoring.livepeer.live/grafana/goto/zop13OFIg?orgId=1
```
  |   | 2024-01-03 17:34:57.481 | ts=2024-01-03T17:34:57.481838188Z msg="received HTTP request" remote=127.0.0.1:60130 proto=HTTP/1.1 method=POST uri=/api/mist/trigger duration=939.986µs status=0 |  
-- | -- | -- | -- | --
  |   | 2024-01-03 17:34:57.473 | ts=2024-01-03T17:34:57.473426935Z msg="received HTTP request" remote=127.0.0.1:60118 proto=HTTP/1.1 method=POST uri=/api/mist/trigger duration=528.616µs status=200 |  
  |   | 2024-01-03 17:34:57.458 | ts=2024-01-03T17:34:57.458237384Z msg="received HTTP request" remote=127.0.0.1:60104 proto=HTTP/1.1 method=POST uri=/api/mist/trigger duration=271µs status=200 |  
  |   | 2024-01-03 17:34:57.407 | ts=2024-01-03T17:34:57.407490592Z msg="received HTTP request" …
```
=> [SRE-221] Reduce logs printend on the default verbosity level

clients/broadcaster_remote.go, clients/callback_client.go, clients/input_copy.go, go.mod, handlers/misttriggers/stream_buffer.go, log/httpLogger.go
The default was to always produce logs which we don't generally need
=> Implement logger for Retryable http client

cluster/cluster.go
Turns out we need to configure a logger for this too to avoid DEBUG messages
=> Turn down Serf memberlist logging

main.go
This is spamming a lot of log lines and so we should turn it off by default
=> Turn off pod-mon by default

clients/input_copy.go, pipeline/coordinator.go, video/profiles.go
Sometimes probing the clip manifest results in zero height and width, so we can probe the original manifest instead to get this info
=> Hack to fix clip resolution parsing

handlers/misttriggers/triggers.go
This is accounting for ~1/3 of Catalyst logs at the moment
=> Stop logging every trigger

pipeline/ffmpeg.go
a couple of days ago we were seeing ~40+ per day, it's down to a handful per day after introducing the retries so hopefully this should get us to essentially zero.
=> Bump retries - still seeing these errors occasionally

handlers/accesscontrol/access-control.go, handlers/accesscontrol/access-control_test.go
This should fix rate limiting, handling it in memory in catalyst instead of Studio
Goes along with https://github.com/livepeer/studio/pull/1982
=> access-control: implement in-memory rate limiting

transcode/transcode.go, video/transmux.go, video/transmux_test.go
Certain input files have a/v sync issues in the output mp4s when they
are played in the browser -- adjusting the playhead fixes the sync
issues. This seems to only occur on browsers and not standalone players
like vlc and qt. It was found that using file based concatenation fixes
this issue. The root cause is under investigation but likely caused by
incorrect timestamps between audio and video tracks. This commit updates
the mp4 generation logic to use stream-based concat for only clips and
use file-based concat for non-clips.
=> use file-based concatenation during mp4 generation for non-clips

api/http_internal.go, config/cli.go, main.go, mapic/mistapiconnector_app.go, mapic/mistmetrics.go, mapic/mistmetrics_test.go, mapic/start_mapic.go
Add `user_id` label to playback-related metrics. We can add more stream-related labels if needed.
Additional comments:
- Adding labels is done on-the-fly (if we see some performance issues, then we can include some caching)
- Mist metrics are exposed together with other metrics under `/metrics`
- Adding labels is done by a simple string replacement, I considered using some Prometheus metrics parsing, but it seemed to be more code and more works, so ended up with this solution
Related PRs:
- https://github.com/livepeer/catalyst/pull/835
- https://github.com/livepeer/livepeer-infra/pull/1931
fix https://linear.app/livepeer/issue/ENG-1581/whitelist-usersaccounts-so-they-never-raise-viewers-by-stream-alert
=> Enrich Mist Prometheus Metrics

handlers/accesscontrol/access-control.go, handlers/accesscontrol/access-control_test.go
Clear the map instead of reassigning the struct to avoid race conditions
=> access-control: fix rate-limit mutex

handlers/geolocation/geolocation.go
The current behaviour meant that the first playback after a stream was deleted would cause it to become active again
=> Don't return a STREAM_SOURCE for suspended / deleted streams

clients/mist_client.go, clients/mist_client_test.go
~~**WARNING: This PR needs to be merged AFTER we solve the issue with multiple ingest Mist nodes ([Discord](https://discord.com/channels/423160867534929930/1204065725896069170/1204740831609753660))**~~
This implements all the functionality we had for the ingest streams, in particular:
- multistream
- heartbeats sent to studio
- metrics collection
=> Fix isIngest for Stream Pull Source

pipeline/coordinator.go, pipeline/ffmpeg.go, test/steps/callbacks.go, transcode/transcode.go, transcode/transcode_test.go, video/probe.go
transcode: drop first segment if a/v tracks have a large offset
For HLS input (recordings), sometimes the first segment can experience a
large delta between the audio and video track's start time (in seconds).
This is mainly because when a streamer begins the stream, the user's
hardware config and OBS settings might cause the video track to start
later than the audio (or vice versa). These segments can be transcoded
but muxing them into an MP4 will fail. For these cases, the first segment
should be dropped from the transcode payload.
=> Handle large a/v offset in first segment of recordings.

mapic/mistapiconnector_app.go
fix https://linear.app/livepeer/issue/PS-227/qiang-we-are-testing-new-camera-firmware-and-observing-strange-issue
=> Forbid starting stream when it's suspended or deleted

handlers/accesscontrol/access-control.go, handlers/misttriggers/user_new.go, middleware/gating.go
Adding custom headers and payload to Gate call, passing them to the webhook in Studio
Currently unsure on how to fetch properly some of the info - in the box some of the items are blank
Potentially we want some of the fields to be set only if the stream `isTrvoAuth=true`
=> access-control: send info payload & headers to gate for webhook trigger

api/http.go, config/cli.go, go.mod, go.sum, handlers/analytics.go, handlers/analytics_test.go, handlers/schemas/AnalyticsLog.yaml, main.go
Add `/analytics/log` endpoint which will be used to pass the analytics from player => analytics pipeline.
Design Doc: https://www.notion.so/livepeer/Studio-2-0-Realtime-Viewership-Backend-2511fd91b0854d09958eed1fa548f447
fix: https://linear.app/livepeer/issue/ENG-1649/implement-http-endpoint-for-periodic-events
Note that:
- Currently, the endpoint does not do anything other than logging, but I'd like to get it into staging, because:
- It will help with the Player integration
- It will help with checking if NGINX is passing geo data correctly
- It will help with checking if the endpoint is exposed correctly with NGINX
- The features is behind the flag `analytics`
- I plan to have it enabled in staging, but disabled for now in prod
- The flag is string not bool, because bool is broken with …
=> Add Analytics Log endpoint

handlers/geolocation/gelocation_test.go, handlers/geolocation/geolocation.go
This is to allow overriding the lat/lon used for load balancing with custom values.
It is needed for the API service to be able to trigger the pull stream to start in a location
close to the pull source, instead of close to where the API is.
The headers themselves are not overridable, since our nginx configuration uses `proxy_set_header`
which forces the value even if one is already present.
I thought about adding some kind of authorization for the override, but it feels like this context
there's no problem if a user tried to override this. They will just get redirected to a worse node. If
they are malicious, they could just hit that (and all other) nodes directly anyway.
Usage: https://github.com/livepeer/studio/pull/2073
=> geolocation: Allow overriding lat/lon with qs

api/http.go
Redirect: We want to redirect `GET /analytics/log` from `https://playback.livepeer.monster/analytics/log` => `https://mdw-staging-staging-catalyst-0.livepeer.monster/analytics/log`, so that player sticks to one catalyst node while sending analytics logs for assets (for stream it's already covered by the playback redirects).
Logging: I'm actually not sure if we should log every analytics log request. A Catalyst node currently can serve ~2.5k viewers, which means that during the peak, we'll log additional `500` logs / second (~2.5k req each 5s). It seems fine, but I'd like to double check with @pwilczynskiclearcode if that's not excessive.
fix https://linear.app/livepeer/issue/ENG-1712/fix-redirects-and-cors
=> Add logging and redirect for /analytics/log requests

handlers/geolocation/geolocation.go
@thomshutt I didn't find any way of tracking what pull URLs were being used so I figured maybe we should remove the log level on this at least while we're still ironing out issues. Useful to see when this is being called for any potential race conditions in the stream startup too.
=> Improve stream pull startup logging

main.go, mapic/mistapiconnector_app.go
We only need to call this on the ingest node, it will then handle shutting down playback streams on other nodes.
=> Only call stop sessions on the ingest node for a stream

api/http.go, handlers/geolocation/geolocation.go, middleware/cors.go
3rd approach to fix redirects to the `/analytics/log` endpoint 🙈 
Changes:
- Redirect `/analytics/log` only if the `Location` header host is different than the host of the given node (prevents infinite redirect loop)
- Add redirects also for HEAD requests
- Add `Access-Control-Expose-Headers: Location` CORS headers
fix https://linear.app/livepeer/issue/ENG-1712/fix-redirects
=> Fix redirects to /analytics/log

clients/manifest.go, clients/manifest_test.go, transcode/transcode_test.go
To optimize playback and TTFF, the output transcode ladder is being updated to use 960p as the threshold i.e. any width/height above 960p will be re-ordered such that it appears second in the list. This is optimal for typical resolutions. For example, if the highest quality is 1920x1080, then it will likely get swapped with 1280x720 in the transcode ladder ordering. Similarly, if the ladder has a highest quality of 1280x960, it will get swapped with the next likely occuring resolution like 1280x720.
=> vod: update transcode ladder for output renditions

go.mod, go.sum, handlers/analytics.go, handlers/analytics/log_processor.go, handlers/analytics_test.go
- Remove `cpu`
- Add `device_model` and `device_brand`
fix https://linear.app/livepeer/issue/ENG-1722/additional-fields-to-kafka-event-cpu-device-brand-device-model
=> Add additional User Agent fields to Kafka Event

go.mod, go.sum, handlers/geolocation/geolocation.go
Currently, when multiple playbacks are started for the same stream, different catalyst nodes start to pull the stream separately which results in a number of issues (like multiple same sessions created for the same stream, broadcaster fails because it's confused by the same `playbackId`/`manifestId`).
To solve it, Studio acts like a distributed lock with the lease timeout. In result what happens is that when the playback is started concurrently, then one of them will fail and need to retry until the stream is replicated between Mist nodes.
Note that we could consider some other distributed lock mechanism than Studio DB, e.g., we can consider replacing Serf with some other distributed in-memory DB which would act as a service discovery, distributed cache, etc. Some options are Redis, …
=> Add lock to stream pull to prevent multiple nodes starting pulling for the same stream

handlers/ffmpeg/ffmpeg.go, pipeline/ffmpeg.go, thumbnails/thumbnails.go, thumbnails/thumbnails_test.go
Tested on staging ✅ 
Todo in future PR: disable thumbs for long recordings/inputs like we do for mp4 generation
=> Refactor thumbs to avoid storage egress

go.mod, go.sum, handlers/geolocation/geolocation.go
It's the same PR that caused the prod failure https://github.com/livepeer/catalyst-api/commit/98aa62799d4391451b3746d7c2f44d20288569df with the following changes:
- Do not lock for the same host (re-entrant lock), this part is already covered by Mist (which does not allow 2 stream pulls on the same node)
- Add feature flag for our test streams => to not break prod again 🙃
=> Lock multiple stream pulls only from different Mist hosts

api/http.go, handlers/healthcheck.go, handlers/healthcheck_test.go, test/cucumber_test.go, test/features/healthcheck.feature
The plan is for this to be available to load balancers to determine whether to route traffic to a node. The current for is simple, but can be extended to check other services on the box, third-party reachability etc.
=> Add healthcheck endpoint

balancer/mist/mist_balancer.go
Prints scores like this: 
```
[2024-04-13 06:05:18] MistUtilLoad (3661948) INFO: Balancing stream video d44ciei8jtwva8
[2024-04-13 06:05:18] MistUtilLoad (3661948) INFO: Winner: fin-prod-catalyst-0.lp-playback.studio scores 2654
```
It might be helpful in debugging routing.
=> mist_balancer: start MistUtilLoad with debug level 4 to print scores

handlers/accesscontrol/access-control.go, handlers/accesscontrol/access-control_test.go, handlers/misttriggers/user_new.go, middleware/gating.go
- When `Origin` is null due to browser policy on 307 and `Referer` is empty, allow without caching and without gate calls
- Fix some mistypes in variable names on userNewPayload
=> access-control: allow redirects without caching

balancer/balancer.go, balancer/mist/mist_balancer.go, balancer/mist/mist_balancer_test.go, handlers/geolocation/geolocation.go, main.go
This PR suppose to reduce [cross-region redirect number](https://livepeer.metabaseapp.com/dashboard/1849-redirects?date_filter=past10hours&ingest_or_playback=playback&user_email=daneli%40trovo.live). After first DNS routing we should mostly keep users in the same region.
[Discord](https://discord.com/channels/423160867534929930/1225093078050934864/1230302133295910912)
=> add Mist load-balancing tags

balancer/balancer.go, balancer/mist/mist_balancer.go, balancer/mist/mist_balancer_test.go, config/cli.go, main.go
https://linear.app/livepeer/issue/PS-515/use-tags-to-add-weight-to-chosen-node-based-on-dns-latency-routing
https://github.com/livepeer/catalyst-api/pull/1231
=> add own-region-tag-adjust cli parameter with 1000 as default

clients/fixtures/mediaconvert_payloads/accelerated.txt, clients/fixtures/mediaconvert_payloads/happy.txt, clients/fixtures/mediaconvert_payloads/no-mp4.txt, clients/mediaconvert.go
Tested on Staging by pushing an FLV and an HEVC file through
=> Save $ by not doing multi-pass encoding in fallback situation

clients/object_store_client.go, go.mod, go.sum, handlers/handlers_test.go, handlers/upload.go, test/features/vod.feature, test/steps/http.go, test/steps/upload_request.go
Annoyingly this relies on having delete permission (to delete the temp file once created) but I couldn't find any other way to achieve this check. Pretty sure there are cases where delete is already needed anyway when we overwrite certain output files.
=> Check write permission for output locations

handlers/ffmpeg/ffmpeg.go, thumbnails/thumbnails.go, thumbnails/thumbnails_test.go
Clip manifests generally have their segment index starting at a non-zero value since they're taken from the middle of a live stream. This was causing the thumb filenames to start with this same index rather than zero. This wasn't great from a user perspective because often they want to just use the filename `keyframe_0.jpg` to get the first frame.
E.g. clip manifest:
```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-TARGETDURATION:8
#EXTINF:2.875,
clip_16.ts
#EXT-X-DISCONTINUITY
#EXTINF:7.125,
clip_17.ts
#EXT-X-ENDLIST
```
Current thumbs output:
```
keyframes_16.jpg
keyframes_17.jpg
```
Fixed thumbs output:
```
keyframes_0.jpg
keyframes_1.jpg
```
=> We always want thumbs index to start from zero as users are expecting this

mapic/mistapiconnector_app.go, mapic/mistapiconnector_app_test.go
Currently we are flooding mist with "getState" calls on startup because we receive a huge backlog of `StreamEvent` messages via serf, to stop this from happening I am introducing rate limiting in the reconcile loop where these messages are received.
=> Rate limit stream reconcile loop

clients/mist_client.go, clients/mist_client_test.go, mapic/mistapiconnector_app.go, mapic/mistapiconnector_app_test.go
Revert my previous rate limiting commit and just add caching to the getState calls. This will then account for both the `StreamEvent` and `StopSessionsEvent` serf events (these subsequently cause a call to `GetState`): 
https://github.com/livepeer/catalyst-api/blob/cad2ccf1b684798b69311b76374fcceaf9f303ad/main.go#L381
=> Mist getState caching

main.go, scripts/pod-mon.sh
To help narrow down usage of Mist and other catalyst processes. 
This script will print a single line json-ish output like this that would make it easier to parse using metabase or loki (?): 
```
{"process": "MistController", "avg_cpu_per_core": 0.214062, "max_cpu_per_core": 13.7, "avg_mem_per_process": 0.05}, {"process": "MistProcLivepeer", "avg_cpu_per_core": 1.04062, "max_cpu_per_core": 12.6, "avg_mem_per_process": 0}, {"process": "MistUtilLoad", "avg_cpu_per_core": 0.15625, "max_cpu_per_core": 5.1, "avg_mem_per_process": 0}, {"process": "MistOutWebRTC", "average_cpu_per_core": 0.0890625, "max_cpu_per_core": 2.9, "avg_mem_per_process": 0}, {"process": "MistInDTSC", "avg_cpu_per_core": 2.07187, "max_cpu_per_core": 15.0, "avg_mem_per_process": 0}, {"process": "MistOutDTSC", …
```
=> pod-mon: re-enable to collect usage metrics

metrics/metrics.go, metrics/monitor_request.go
We recently started caching mist API requests so I want to be able to monitor the request count especially during deploys where we had the problems before
=> Add request count to client metrics

metrics/metrics.go, metrics/monitor_request.go
We already have a count metric automatically created from the duration metric.
=> Remove request count client metric

video/probe.go, video/probe_test.go
We no longer want to support this format for VOD, so will start explicitly rejecting it at the point of ingest.
=> Remove prores support

config/cli.go, handlers/accesscontrol/access-control.go, handlers/accesscontrol/access-control_test.go, handlers/accesscontrol/data_client.go, main.go
Related to: https://www.notion.so/livepeer/Cap-50k-Fishtank-viewers-a828ef8d037a4f27b9a6769d91c50b23
**Related PRs:**
- https://github.com/livepeer/livepeer-data/pull/194
- https://github.com/livepeer/studio/pull/2223
**Comments:**
- The solution is not 100% bullet-proof (we may encounter viewers exceeding the limit); that's done on purpose, because we prefer to allow a few viewers above the limit rather than increasing the TTFF. The reasons why viewers may be allowed above the limit:
- data about the concurrent view count is note refresh (livepeer data takes data from Victoria Metrics nad it has some delay)
- we cache the concurrent view count for 30s
- we refresh the concurrent view count **after** allowing the user (because we don't want to make a sync call)
- viewer limit may not be …
=> Add viewer limit

clients/object_store_client.go, pipeline/ffmpeg.go, thumbnails/thumbnails.go, video/probe.go
This fixes 2 misuses of the backoff lib found in `catalyst-api` code:
- Re-using singleton instances of a backoff. They are not meant to be shared so we should create one on every call
- Not calling `Reset` on the exponential backoff after configuring it. This (confusing) requirement is necessary if we change the `IniitalDelay`. By not calling it we were basically ignoring any changes and going with the default 500ms.
=> backoff: Fix usage of backoff library

handlers/analytics.go, handlers/analytics/log_processor.go
Fix https://linear.app/livepeer/issue/ENG-2135/add-time-warning-ms-to-catalyst-api
=> analytics: Add 'time_warning_ms' field

clients/arweave_ipfs_s3.go, clients/input_copy.go, clients/object_store_client.go, clients/object_store_client_test.go, errors/errors.go, go.mod, go.sum, handlers/playback.go, playback/playback.go, transcode/transcode.go
Currently, 404 errors are not treated any differently on clients code. This means that if we get a 
404 error from a storage we keep retrying until the end of the retry policy. This was a problem for
the storage fallback code so I'm starting with this refact, which improves behavior anyway.
After this:
- They stop backoff retry loops (as long as it gets returned or wrapped)
- If they're included in the final error of the job, they will make the `unretriable` flag be `true` so studio doesn't retry
- The returned errors can be detected as 404s easily (necessary for storage fallback logic)
- Implement a "not exist" error in the lib https://github.com/livepeer/go-tools/pull/121, which is consumed here.
- Create a `ObjectNotFoundError` type in catalyst. This will be especially useful for the …
=> clients: Handle not found errors gracefully

clients/manifest.go, pipeline/external.go, thumbnails/thumbnails.go, thumbnails/thumbnails_test.go
We need thumbs from mediaconvert to have feature parity across the two pipelines.
=> Thumbs for mediaconvert

clients/arweave_ipfs_s3.go, clients/input_copy.go, clients/object_store_client.go, clients/object_store_client_test.go, errors/errors.go, go.mod, go.sum, handlers/playback.go, playback/playback.go, transcode/transcode.go
Need to figure out the retry logic before re-rolling this. Sometimes we need to retry 404s due to eventual consistency of storage.
This reverts commit 7a3e994b944d3dbf6ca4e67d21e8bc7fe99ad3f3.
=> Revert "clients: Handle not found errors gracefully (#1302)"

handlers/accesscontrol/access-control.go, handlers/accesscontrol/access-control_test.go
- Remove rate limit and rate limit cache
=> access-control: viewers limit

clients/mist_client.go, main.go
We need to enable running catalyst-api on a separate machine to where Mist is running. If Mist is run on a non-localhost machine, it requires a single authentication request. This PR adds an authentication if the command send to Mist failed.
Related to Zero Impact Catalyst API Deployments, we want to run catalyst-api separately to Mist.
Design Doc: https://www.notion.so/livepeer/Zero-Impact-Catalyst-API-Deployments-c2b15232f3a2450ba3e4803130ecd2be?pvs=4#5ce68dfca1c341bfb6b21361d36d19df
=> Add Mist authentication

cluster/cluster.go, handlers/geolocation/geolocation.go, handlers/geolocation/geolocation_test.go
This change is refactoring-only, it does not introduce any functional changes.
It improves the Cluster interface abstraction, two of its functions were used only inside geolocation, so it's better to move it there and keep it package-private.
This change is related to the Zero Impact Catalyst API Deployments, because I plan to make a split between stateful and stateless catalyst-api at the cluster level. 
Design Doc: https://www.notion.so/livepeer/Zero-Impact-Catalyst-API-Deployments-c2b15232f3a2450ba3e4803130ecd2be?pvs=4#5ce68dfca1c341bfb6b21361d36d19df
=> Refactor cluster abstraction: remove Member() and ResolveNodeURL()

balancer/mist/mist_balancer.go, cluster/cluster.go, main.go
The context for this change is that we sometimes see multiple MistUtilLoad instances running, sometimes zero instances running. Therefore we should always make sure that only 1 instance is running all the time.
This change will also make simpler to implement Zero Impact Catalyst API Deployments, because we'll statically configure MistUtilPort. Additionally, this change includes periodic members refresh (in case the serf member event is missed).
Design Doc: https://www.notion.so/livepeer/Zero-Impact-Catalyst-API-Deployments-c2b15232f3a2450ba3e4803130ecd2be?pvs=4#5ce68dfca1c341bfb6b21361d36d19df
Tagging @iameli , because you may remember the context of why we're running MistUtilLoad using a random port.
=> Use constant port for MistUtilLoad and reconcile periodically to make sure it's running

balancer/mist/mist_balancer.go
For some reason `MistUtilLoad` sometimes needs a stronger kill with `-9` :)
=> Add '-9' to pkill command while killing the previous MistUtilLoad process

config/cli.go
With the existing check it's impossible to pass anything that is not resolved to an IP Address. In particular, it fails to run locally inside Docker container and parse 'host.docker.internal'.
=> Relax the condition for parsing AddrFlag

clients/mist_client.go, handlers/misttriggers/trigger_broker.go, main.go
This change is refactoring-only, no functional changes included.
The rationale is that MistClient can execute commands on any remote Mist server and setting up triggers (or having a field TriggerCallback) breaks this abstraction.
=> Refactor SetupMistTrigger()

balancer/mist/mist_balancer.go, balancer/mist/mist_balancer_test.go, main.go
We want to allow running catalyst-api separately to catalyst, so MistUtilLoad needs to be accessed remotely.
Design Doc: https://www.notion.so/livepeer/Zero-Impact-Catalyst-API-Deployments-c2b15232f3a2450ba3e4803130ecd2be
=> Allow using a remote MistUtilLoad for load balancing

.github/workflows/docker.yaml, Dockerfile
We plan to enable running catalyst-api separately to catalyst, therefore it needs its own Docker image. 
Note that it I didn't include `w3` tool, because Web3 Storage has shut down, so we should remove the support for Web3 Storage.
Design Doc: https://www.notion.so/livepeer/Zero-Impact-Catalyst-API-Deployments-c2b15232f3a2450ba3e4803130ecd2be?pvs=4#5ce68dfca1c341bfb6b21361d36d19df
=> Add Docker build

pipeline/coordinator.go, pipeline/coordinator_test.go
Currently there's no way of distinguishing between the different reasons when MP4 generation doesn't happen and so this extra logging means we will now always be able to differentiate.
=> Add logging about reason for not generating an MP4

api/http_internal.go, config/cli.go, main.go
From now on, we'll be able to run catalyst-api in 3 modes:
- `all`: the same as before
- `cluster-only`: managed MistUtilLoad and Serf only (intended to use inside Catalyst)
- `api-only`: stateless API only (intended to get deployed separately from Catalyst)
Related to the effort of deploying `catalyst-api` separately from `catalyst`. Design Doc: https://www.notion.so/livepeer/Zero-Impact-Catalyst-API-Deployments-c2b15232f3a2450ba3e4803130ecd2be?pvs=4#5ce68dfca1c341bfb6b21361d36d19df
=> Add option for running catalyst-api as a stateless service

handlers/analytics.go
Alternatively, we could use `withLogging()`, but I'm afraid of the number of logs if there are a lot of /analytics/log sent
=> Add logging to /analytics/log errors

handlers/analytics/log_ext_data.go, handlers/geolocation/geolocation.go, mapic/mistapiconnector_app.go, mapic/utils.go, mapic/utils_test.go
It causes the prod failure, because of the cascading failures
Related Discord thread: https://discord.com/channels/423160867534929930/1265176750544130068/1265181494763327562
=> Add 1s cache for lapi.GetStreamByPlaybackID()

handlers/analytics.go, handlers/analytics/log_processor.go
**Improvements:**
1. Increase the internal buffer size from 5000 analytics logs to 25000 analytics logs (this will delay the 5xx to more Kafka write errors before we start to see them)
2. Update warning message to not include a word `error`
3. Add retries to writing messages to Kafka
Fix https://linear.app/livepeer/issue/PS-721/5xx-alerts-sto-prod-catalyst-4lp-playbackstudio-prod-catalyst-4
=> Improve handling Kafka write errors

mapic/utils.go
@victorges  made a good comment after I already merged https://github.com/livepeer/catalyst-api/pull/1342
> don't we need to remove the e.stream != nil check from L35 and L47 if we want to cache errors?
https://github.com/livepeer/catalyst-api/pull/1339/files#diff-3ab4c68e5efa7f23725f338aae519ee0613c23dd471ecc3a45ac4f0488bd985cR35
i mean. we are caching errors. we're just not using that cache haha
=> Cache also errors when caching lapi.GetStreamByPlaybackID()

handlers/upload.go, handlers/upload_test.go
This PR began as just wanting to add validation for when people are accidentally passing in unix timestamps in seconds rather than milliseconds, but increased in scope when I found that we were using the existing clip validation method to determine whether a request _was_ a clipping request, rather than passing the errors produced back to the user.
=> Better clipping request validation

handlers/upload.go, handlers/upload_test.go
It turns out that Studio doesn't pass in a "clip" output in the request, but it does always have a Playback ID in the clipping strategy, so use that instead.
=> Better method for detecting clipping requests

handlers/analytics.go
This is to avoid spamming log lines and to ease pressure in situations where we're getting thousands of messages spammed simultaneously.
Also adds more info to the log line to try and understand the root cause of what we're getting spammed with.
=> Give up on remaining analytics messages when we fail to push to the buffer

handlers/analytics.go
i was getting tired of seeing `%v` appear in logs:
```
W0731 05:15:49.119430 2566432 analytics.go:117] cannot parse geo info from analytics log request header, err=%vmissing geo headers: [X-Region-Name]
```
=> analytics.go: Fix typo in error message formatting

pipeline/external.go, thumbnails/thumbnails.go
We saw a case in prod where this target URL was still nil. Should have had nil checks from the start anyway to avoid any panics.
=> Add nil checks in thumbnail code

clients/broadcaster_local.go, clients/callback_client.go, errors/errors.go, pipeline/coordinator.go, pipeline/ffmpeg.go, transcode/transcode.go
If we return internal error messages to the requester there is the possibility to reveal internal secrets etc so we should just log them instead. This will also be more useful for debugging since we can query logs for this info.
=> Log internal errors rather than returning them to requester

handlers/analytics.go, handlers/analytics_test.go
Geo header X-Region-Name is not available in all regions, therefore we should treat it as optional.
=> analytics: Don't log on missing X-Region-Name header

api/http_internal.go, config/cli.go, handlers/events.go, handlers/events_test.go, main.go
This PR includes 2 ugly changes that are needed to deploy catalyst-api separately from catalyst:
The events are used, e.g.,  to notify multistream target change and to nuke a stream. They are received in catalyst, then propagated to all nodes using Serf, and then forwarded to each catalyst-api instance. The change included here is to expose `/api/events` not only in catalyst, but also in catalyst-api (which then proxies the request to catalyst). It's needed because Studio API communicates events with catalyst-api (not directly with catalyst).
Alternatively, we could have two catalyst params in Studio API (but I think it would be "even more" ugly.
Catalyst needs to communicate with each corresponding Statelss Catalyst API. E.g. `staging-catalyst-0` needs to communicate with …
=> Improvements for Zero Impact Catalyst API Deployments

api/http_internal.go
We still need to have the `/metrics` endpoint to report the catalyst-api version used inside catalyst
=> Fix /metrics for cluster-only mode

clients/input_copy.go, clients/manifest.go, clients/manifest_test.go, thumbnails/thumbnails.go
Thumbnails were broken for recording fallback because it wasn't expecting absolute URLs in the manifest.
Also tweaked the fallback logic to just return the original manifest URL if everything was found on the primary, I kinda prefer to keep the happy path using the same manifest we're used to rather than writing a new playlist for every recording job. There may be weird edge cases like this thumbnails issue, and would rather keep the normal happy path unchanged in that way.
=> Fix thumbs for recording fallback

main.go
The catalyst node needs to have an address to the corresponding catalyst-api service. It's set with CATALYST_API_CATALYST_API_URL env variable, but to apply a new env variable we would need to restart the catalyst node, so the hack is to resolve it automatically in the code.
=> Update hack for resolving catalyst-api url from catalyst

balancer/balancer.go, balancer/mist/mist_balancer.go, balancer/mist/mist_balancer_test.go, config/cli.go, handlers/healthcheck.go, main.go
This is a hack to allow us to re-route a portion of traffic from an overloaded region to alternative nodes. We have a region where we'd like to balance more traffic away from onto alternative regions instead.
For example to re-route 25% of `regionX` to a selection of other nodes:
```
lb-replace-host-match = regionX
lb-replace-host-percent = 25
lb-replace-host-list = otherNode1,otherNode2
```
=> Implement percentage node replacement for load balancer

api/http_internal.go, handlers/events.go, handlers/misttriggers/trigger_broker.go, handlers/proxy.go, main.go
I always thought that catalyst-api dynamically sets Mist triggers. This is true, but this config gets overwritten with the default config present [here](https://github.com/livepeer/livepeer-infra/blob/a82a30fcd185fc6b9fc3fa52412c8608725b47c4/values/catalyst.values.yaml#L191) every time MistController restarts of the config file is changed. The only reason it worked in prod is that our dynamic Mist Trigger configuration is exactly the same as the config map configuration.
I think it's super misleading and it led to the issues when I tried to use the standalone catalyst-api, because my config got overwritten and all stopped working at some point.
-----
First of all, I suggest removing this whole dynamic mist triggers setup (to avoid further confusion). Secondly, we need to think how to …
=> Proxy Mist triggers from catalyst to catalyst-api and remove dynamic Mist Trigger Setup

balancer/mist/mist_balancer.go, balancer/mist/mist_balancer_test.go
When catalyst-api is deployed standalone, then MistHost is not "127.0.0.1" and this redirect does not work
=> geo redirect: Redirect self-node in case of "127.0.0.1" (not MistHost)

handlers/misttriggers/trigger_broker.go, main.go
This broke catalyst E2E Tests. I plan to fix it later, but for now let's revert this removal
=> Revert removal of dynamic Mist trigger setup

mapic/mistmetrics.go, mapic/mistmetrics_test.go
When the catalyst-api was run inside catalyst, we used VM Agent to collect the metrics and then added the `catalyst=true` label in the [VM Agent config](https://github.com/livepeer/livepeer-infra/blob/89b7549035488359fee8761375ffba9e3b3c2856/values/catalyst.values.yaml#L176).
Now, for the standalone Catalyst API we use Kubernetes prometheus scrape which does not add this label. At the same time, we use this label in a really high number of charts, so the simple fix is to just add this label here.
An alternative would be to update all Grafana charts that use `catalyst=true` metric with a condition `app_kubernetes_io_name="catalyst-api"`. However I see there are really a lot of these charts, so I'm not sure there is a simple way to update  them all.
=> Add 'catalyst=true' label to Mist-enriched metrics

cluster/cluster.go
Both the [reconcile loop](https://github.com/livepeer/catalyst-api/blob/eaa3c06f3dc0ca35eb8c6c2c0e42d3312164a333/main.go#L391) and the [code](https://github.com/livepeer/catalyst-api/blob/fd526881be1bf1a0c52073f426657a27fe14a7b3/cluster/cluster.go#L125) that initialises the `c.serf` variable start in parallel so there's a chance for `serf` to be nil when `MembersFiltered` is called.
=> Add nil check for serf

clients/mist_client.go, handlers/accesscontrol/access-control.go
It addresses the problem we discovered during catalyst deployment.
Execute session invalidate HTTP requests to Mist:
1. Outside locks
2. In a separate goroutine
3. With timeout
In theory any of these points would solve the issue, but it's better and safer to implement all of them.
When we deployed catalyst, then in most cases `USER_NEW` trigger was blocked and we saw the following error:
```
MistOutFLV:video+9cfc2xmk4pvz6jo7 (958765) FAIL: STREAM_SOURCE trigger: http://127.0.0.1:7979/api/mist/trigger (blocking) failed to execute (Timed out), using default response: true
```
1. In the [`periodicRefreshIntervalCache()` func](https://github.com/livepeer/catalyst-api/blob/fdad3c74a7bb39cc293523f505444994b7dfd976/handlers/accesscontrol/access-control.go#L121) we acquired a lock and made an …
=> Fix locking during session invalidation

clients/object_store_client.go, handlers/upload.go
I'm seeing this fail occasionally in prod since storage providers can be a bit slow even with a small json file.
Also fixed creds leaking in log line, the filepath join was stripping a `/` on `http://` which meant the log redact function couldn't parse it as a url.
=> Increase timeout for write permission check

mapic/mistmetrics.go, mapic/mistmetrics_test.go
We used to add them with VM agent, but when catalyst-api is run standalone, then they didn't exist.
This is the related dashboard to fix: https://eu-metrics-monitoring.livepeer.live/grafana/d/000000016/mist-global-overview?orgId=1&from=1723593600000&to=now&refresh=1m
=> Add missing Mist metrics labels

mapic/mistapiconnector_app.go
It turns out that Mist has a special parsing of these push URLs which is not a regular URL parsing. It removes anything after the last `?` in the URL and uses that as its config. If there are multiple `?` in the URL (e.g. query-string already existed in target URL), it will strip only (from) the last one and keep the previous.
So instead of merging Mist's qs with the existing ones, we actually need to create a separate `?` section for Mist. This guarantees both that Mist gets its config properly, as well as that it preserves the URL to call the target service.
=> mapic: Fix multistream target URL `?` handling

middleware/gating.go, thumbnails/thumbnails.go, thumbnails/thumbnails_test.go
The VTT file should have had a blank line after the first line, it parses successfully in https://w3c.github.io/webvtt.js/parser.html now
=> Fix VTT format

handlers/analytics.go, handlers/analytics/log_processor.go, handlers/analytics_test.go, handlers/schemas/AnalyticsLog.yaml
Player sends the field `message` (not `error_message`), so we need to update it so that it's correctly propagated to Kafka.
=> Rename analytics field error_message => message

middleware/shell.go
High CPU/memory are easier to investigate during the alert as we don't have per process CPU/memory usage metrics on grafana. There are just per-pod metrics and mist works as hundreds of processes, separate for ingest, playback, load-balancing, etc.
There are logs from [pod-mon.sh](https://github.com/livepeer/catalyst-api/blob/main/scripts/pod-mon.sh) that we start from [catalyst-api](https://github.com/livepeer/catalyst-api/blob/main/main.go#L343-L346) but I they started missing on [sto-1 and sto-3](https://eu-metrics-monitoring.livepeer.live/grafana/goto/i2-xLZGNR?orgId=1) for some reason. On sto-1 the catalyst-api has been running for 11 days and logs stopped appearing on 2024-11-02 17:48:43 with a log line cmd: failed to start [pod-mon.sh](http://pod-mon.sh/). It also lines up with the …
=> pod-mon.sh and mist-cleanup.sh to run forever even sometimes crashing

balancer/balancer.go, balancer/balancer_stub.go, balancer/catabalancer/catalyst_balancer.go, balancer/catabalancer/catalyst_balancer_test.go, balancer/mist/mist_balancer.go, handlers/events.go, main.go
Now that we're using a DB for the node stats we can remove the internal state for this data. The only state we still maintain in catabalancer is the list of nodes updated by serf.
=> Refactor to remove local catabalancer state

balancer/balancer.go, main.go
I think to be safe we should execute these background calls in a separate goroutine, I don't want the risk of slow DB calls slowing down the real responses. I want to see the impact of the DB calls on the execution times, I'm not sure what size DB is appropriate at the moment.
=> Run background catabalancer calls really in the background

balancer/catabalancer/catalyst_balancer.go, balancer/catabalancer/catalyst_balancer_test.go, config/cli.go, main.go
Background load balancer calls were seen taking multiple hours in prod (only on the regions with higher request rate) due to the relatively small number of connections available: https://github.com/livepeer/catalyst-api/blob/f0d8c83827abe68af240afa1a8dcfc894ec7c259/main.go#L241 so cache the results for a short time (500ms currently)
=> Cache node stats db results

balancer/balancer.go, balancer/catabalancer/catalyst_balancer.go, balancer/catabalancer/catalyst_balancer_test.go, events/events.go, events/events_test.go, main.go, metrics/metrics.go
I found that even with caching there were still requests to the DB taking 1+ seconds, this would happen when a number of concurrent requests hit a cache expiry. So instead of letting these all make a request to the DB, allow one through while making the other wait behind.
=> DB query coalescing - block other requests while refreshing the cache

balancer/catabalancer/catalyst_balancer.go, metrics/metrics.go
In prod I saw stale metrics being ignored so we need to check the durations of the send operation and add an appropriate timeout.
=> Add timeout for node metric sending
