.github/workflows/test.yaml
Makefile
README.md
cmd/http-server/http-server.go
go.mod
handlers/handlers.go
middleware/auth.go
middleware/middleware_test.go

See this thread for context on the rename: https://discord.com/channels/423160867534929930/991388659699949669/1004599546933948486

Rename dms* -> catalyst*

---

cmd/http-server/http-server.go
go.mod
go.sum
middleware/logging.go

Added Logging Middleware

---

cmd/http-server/http-server.go

Re-merging this one cause we ended up reverting it on a rebase in #20

Run on 0.0.0.0 instead of localhost (#19)

---

clients/mist_client.go
clients/mist_client_mock.go
clients/mist_client_test.go
go.mod
go.sum
handlers/misttriggers/push_end.go
handlers/transcode.go

This is a precursor to using source information to check against the info Mist sends us on completion and also theoretically allows us to communicate information back to Studio about media with > 1 video / audio tracks.

Parse Mist stream info into a proper struct

---

handlers/misttriggers/recording_end.go
handlers/misttriggers/recording_end_test.go
handlers/misttriggers/triggers.go

Doesn't do anything yet, but all the boilerplate we'll need to handle this trigger (which should make this following PR easier to read).

Create basic RECORDING_END trigger handler

---

handlers/misttriggers/recording_end.go
handlers/transcode.go
transcode/transcode.go
transcode/transcode_test.go

Send Studio callbacks during + after transcoding process

---

transcode/manifest.go
transcode/manifest_test.go
transcode/transcode.go
transcode/transcode_test.go

Still a lot of neatening up we can do around how we build URLs etc. but this is tested on Canary and works

Write transcoded segments to storage for local B

---

transcode/manifest.go
transcode/manifest_test.go
transcode/transcode.go

Order master playlist by descending bitrate or resolution if bitrate is the same.
Still need to confirm that the bandwidth is correctly sourced.
Closes #94

Order master playlist by bitrate and resolution

---

transcode/manifest.go
transcode/manifest_test.go
transcode/transcode.go
transcode/transcode_test.go

Fix 0 bandwidth on master playlist

---

clients/broadcaster.go

This resolves https://github.com/livepeer/catalyst-api/issues/183

Log Broadcaster response body when we get an HTTP error code

---

clients/arweave_ipfs_s3.go
clients/arweave_ipfs_s3_test.go
handlers/upload.go

This resolves https://github.com/livepeer/catalyst-api/issues/197

Also copy IPFS URLs to storage

---

handlers/misttriggers/recording_end.go

This addresses https://github.com/livepeer/catalyst-api/issues/196

Wait for segmenting upload to finish

---

clients/mist_client.go
clients/mist_client_mock.go
clients/mist_client_test.go
handlers/misttriggers/recording_end.go
handlers/upload.go

\#Fixes https://github.com/livepeer/catalyst-api/issues/201
The changes here requires the following Mist changes here: 
https://github.com/DDVTECH/mistserver/pull/135

Allow option to specify a DTSH output path

---

transcode/transcode_test.go

Have realistic master manifest bandwidth on test

---

clients/arweave_ipfs_s3.go
clients/object_store_client.go
errors/errors.go
handlers/upload.go
metrics/metrics.go
middleware/capacity_test.go
pipeline/coordinator.go
pipeline/external.go
pipeline/handler.go
pipeline/mist.go
test/steps/http.go
transcode/transcode.go

Just improving the core coordinator metric to be more informative. Might be all we need to evaluate pipelines.

pipeline: Measure separate handlers success rate and performance

---

handlers/schemas/UploadVOD.yaml
handlers/upload.go
pipeline/coordinator.go
pipeline/coordinator_test.go

Created a new field on the request and the simple logic in the controller to use it if provided.

pipeline,handlers: Allow overriding strategy on upload request

---

clients/mediaconvert.go

Addresses https://github.com/livepeer/catalyst-api/issues/311

Retry for "Acceleration fault" errors

---

clients/mediaconvert.go

Certain file servers may close the connection when catalyst-api is in the process of downloading the source file - an example is IPFS based links where the gateway and pinning servers may be different and lead to erratic connection issues. Instead of giving up, catalyst-api will now attempt to transcode using the source URL directly since the AWS/MediaConvert API has built-in support for retries. This will ensure more successful transcode sessions albeit missing a copy of the source input file which is only required for debugging.
Note: a follow-up PR will be used to implement download-manager style retries in catalyst-api.
Fix #323

clients/mediaconvert: transcode with source url if download and upload to S3 fails

---

clients/callback_client.go
pipeline/coordinator.go

fix https://github.com/livepeer/catalyst-api/issues/325

Add logging stacktrace to panic recovery

---

clients/mediaconvert.go
clients/mediaconvert_test.go
clients/s3.go
video/probe.go

To fix probing videos where the header is at the end.

ffprobe with a presigned URL

---

clients/callback_client_status.go
clients/mediaconvert.go
clients/mediaconvert_test.go
clients/s3.go
clients/transcode_provider.go
pipeline/coordinator.go
pipeline/coordinator_test.go
pipeline/external.go
transcode/transcode.go

fixes:
https://github.com/livepeer/catalyst-api/issues/389
https://github.com/livepeer/catalyst-api/issues/400

add mp4 outputs to status message

---

clients/mediaconvert.go

This reverts commit 5d338d0d8524f2356377e993bdae283dd2d6ddc0.

Revert "revert studio message change (#420)"

---

clients/callback_client_status.go
clients/mediaconvert.go
clients/mediaconvert_test.go
video/probe.go

* refactoring some bits in ffprobe logic
* add probing logic to output MP4 files
* also helps in moving away from MC pipeline and towards catalyst dominance  
Fix #429 
Fix #391

ffprobe updates

---

go.mod
go.sum

Related discussion in https://github.com/livepeer/catalyst/issues/397

Change Transcode API Task output format

---

go.mod
go.sum
transcode/transcode.go
video/transmux.go

Final PR to actually transmux concatenated ts segments and upload. This is a first iteration and goal is to keep it simple first and then add more features like asynchronous processing via ffmpeg and/or better memory management (if required).

transmux ts segments into mp4

---

handlers/schemas/UploadVOD.yaml
pipeline/coordinator.go
pipeline/external.go
pipeline/ffmpeg.go
pipeline/ffmpeglivepeer.go
pipeline/mist.go
test/features/vod.feature
test/steps/http.go
test/steps/upload_request.go

Wanted to get this out there for review so that we get agreement on the pipeline naming etc. and make future PRs smaller and more readable.
On naming - should we just call it the "livepeer" pipeline? We're a little hamstrung by having called the other one the "catalyst" pipeline and wanting to have both of these in the code until we gain confidence in this new one.

Skeleton code + tests for segmenting with ffmpeg

---

clients/callback_client_status.go

Related Linear: https://linear.app/livepeer/issue/VID-102/add-metrics-to-transcode-api-tasks
FYI: @ecmulli

Add request ID to Transcode API Task outputs

---

test/cucumber_test.go
test/features/playback.feature
test/steps/http.go
test/steps/init.go
test/steps/steps.go

This is to add test coverage for the change in bf5f658f

Verify type field is set on Gate API call

---

api/http_internal.go
config/config.go
handlers/ffmpeg/ffmpeg.go
handlers/ffmpeg/ffmpeg_test.go
handlers/handlers_test.go
main.go
pipeline/coordinator.go
pipeline/ffmpeg.go
test/cucumber_test.go
test/features/vod.feature
test/steps/ffmpeg.go
test/steps/http.go
test/steps/steps.go
video/segment.go

This commit gets the FFMPEG pipeline as far as writing the source segments to storage (and a corresponding integration test).
Still TODO in future PRs:
- Kick off transcode pipeline off the back of this + integration test steps for this
- Create "fallback" version of this pipeline
- Check if there are any pipeline-specific metrics we want to add

Segmenting using FFMPEG

---

handlers/ffmpeg/ffmpeg.go
handlers/ffmpeg/ffmpeg_test.go
pipeline/coordinator.go
pipeline/ffmpeg.go
test/cucumber_test.go
test/features/vod.feature
test/steps/broadcaster.go
test/steps/http.go
test/steps/steps.go
test/steps/upload_request.go

Still TODO in future PRs:
- Create "fallback" version of this pipeline
- Check if there are any pipeline-specific metrics we want to add
- Check for callbacks in integration tests

Add transcoding to FFMPEG pipeline

---

pipeline/ffmpeg.go

This is sent by the coordinator with all information that Studio needs, so we shouldn't be sending it here

Don't send a duplicate Completion callback

---

test/cucumber_test.go
test/features/vod.feature
test/steps/callbacks.go
test/steps/steps.go
test/steps/upload_request.go

Basic structure to start testing callbacks in the integration tests. I've only added a check of callback type so far, but it should now be easy to add more complex checks.

Test callbacks in integration tests

---

balancer/balancer.go
balancer/balancer_test.go

Followup to https://github.com/livepeer/catalyst-api/pull/670
That rewrote the URL when pushing in and out of the load balancer but didn't rewrite it when actually handling balancing requests, whoops. This fixes that.

balancer: make sure to rewrite local node on balancing requests!

---

config/cli.go
main.go
scripts/mist-cleanup.sh

We had issues in prod when it was first introduced a few weeks ago. The script has now been fixed so we're re-introducing it. Will let it soak in staging prior to launching in prod.

re-enable mist cleanup script

---

mapic/mistapiconnector_app.go

The right way to reject a stream from PUSH_REWRITE:
1. Respond with an empty string
2. Use "Transfer-Encoding: Chunked" to work around a Mist bug
This adds a helper reject() function in the handler that makes it very easy to do so.

mapic: use Transfer-Encoding: chunked when rejecting streams

---

pipeline/coordinator.go
pipeline/external.go

Previously this was only being set in the mediaconvert pipeline

Fix setting source bytes and duration

---

clients/callback_client.go
clients/callback_client_status.go
config/cli.go
config/config.go
main.go

I believe we don't use this record event callbacks, but I might be wrong, so please double check @thomshutt @iameli

Clean up unused code

---

balancer/balancer_test.go
handlers/geolocation/gelocation_test.go
handlers/geolocation/geolocation.go

more context behind the change here: https://discord.com/channels/423160867534929930/1115311846203850913/1124001667541651567

geolocation: Use `307` status code for redirects

---

go.sum
main.go

to help us debug memory leaks in prod

enable pprof handler

---

transcode/transcode.go

It was discovered that pods were hitting OOM errors when long running livestreams and their corresponding recordings were being processed. In the recording generation stage, the ts segments are buffered in memory and then written to disk to generate the mp4. This poses an issue for livestreams that are several hours in duration. Additionally, it doesn't make sense to generate mp4s for all renditions for HLS inputs.
This commit updates the logic such that an mp4 will be generated for only the highest bitrate profile.
Fix VID-127

transcode: generate mp4s for only the highest bitrate rendition for HLS input

---

video/clip.go

Part 2 in series of Clipping related PRs. 
This change adds logic to take any segment and clip it to the start/end time specified and also re-encodes it with some x264 args to re-encode and place I-frames at the right intervals. 
TODO: an integration test will be added in a separate PR.

clipping: clip a segment

---

clients/input_copy.go

This is to guard against an issue we had with recordings where we saw an empty segment at the end of a manifest.
Verified this on staging with a problematic input: https://lp-us-catalyst-recordings-com.storage.googleapis.com/hls/b7caqhzl06ma2iqn/e0e9a30f-769c-4e50-9b69-2cf0ac97e68c/output.m3u8

Ignore empty files when copying multiple files

---

clients/manifest.go
clients/manifest_test.go
transcode/transcode.go

transcode/manifest: generate master fmp4 playlists and upload to object-store

Generate master playlists for fragmented-mp4 media playlists

---

clients/input_copy.go
config/cli.go
main.go
pipeline/coordinator.go
pipeline/ffmpeg.go
pipeline/ffmpeg_test.go
test/steps/broadcaster.go

This reverts commit 62c828ba0d75802642b3dd5dd64fb58a95b9af3b.

Revert "Skip source copy for HLS input (#818)"

---

balancer/balancer.go
config/cli.go
handlers/geolocation/gelocation_test.go
handlers/geolocation/geolocation.go
main.go
metrics/metrics.go

This reverts commit b5a530d514d23c06b5ad64abfc5a5f29dd637fd0.

[SRE-160] CDN redirect only for /hls

---

pipeline/ffmpeg.go
pipeline/ffmpeg_test.go

I needed to adjust the source playback logic slightly to be able to support writing the segmented video to a different storage bucket than the final outputs

Support alternative source output bucket

---

middleware/cors.go

cors: add Access-Control-Allow-Methods: *

---

.github/workflows/test.yaml

Reverts livepeer/catalyst-api#867

Revert "build(deps): bump codecov/codecov-action from 3 to 4"

---

pipeline/ffmpeg.go
pipeline/ffmpeg_test.go

Some uploaded sources have very high bitrates which wouldn't be playable over most internet connections so we should limit source playback to sensible bitrates.

Limit source playback bitrate

---

handlers/accesscontrol/access-control.go

The error from `decodeJwt` wasn't being logged in any way so makes it impossible to understand the failures. Instead of logging in that function we can pass the error upwards since we log the result higher up the chain

Wrap the error from decoding the JWT

---

cache/cache.go
config/config.go
main.go
middleware/capacity.go
middleware/capacity_test.go

Use separate limits for regular-vod vs clipping-vod jobs

---

mapic/mistapiconnector_app.go

Reverts livepeer/catalyst-api#956

Revert "Move setActive(true) from the trigger 'PUSH_REWRITE' to 'STREAM_BUFFER'"

---

pipeline/ffmpeg.go
thumbnails/thumbnails.go

For now keep it simple, at a later date we can make sure we wait for completion at the end of the vod job

Push thumbnail generation to background

---

pipeline/ffmpeg.go
test/cucumber_test.go
test/features/vod.feature
test/steps/broadcaster.go
test/steps/http.go
test/steps/steps.go
test/steps/upload_request.go
thumbnails/thumbnails.go

I found a couple of cases where the thumbs completed a couple of mins after the rest of the job, so I'm adding this to wait for the background go-routine to finish
I will add a cucumber test for this asap 👍 so far tested on local box environment

Wait for thumbs to complete

---

thumbnails/thumbnails.go

Add thumbnail upload retries and increase the timeout after seeing pretty high average response times from Storj

Add thumbnail upload retries

---

balancer/catabalancer/sysstats.go

TODO: need a separate PR to add `vnstat` to our pods
~~TODO: read NIC speed directly from /proc filesystem (need to confirm if this is accurate)~~

catabalancer/systats: add bw usage info

---

balancer/catabalancer/catalyst_balancer.go
balancer/catabalancer/catalyst_balancer_test.go
config/cli.go
main.go

Extract catabalancer timeouts to cli args

---

cluster/cluster.go
config/cli.go
main.go

There's a lot of these options, huh?

cluster: Add SerfMaxQueueDepth

---

balancer/balancer.go
main.go

Allow the option to run catabalancer in playback or ingest only modes

Expand catabalancer running modes

---

balancer/catabalancer/catalyst_balancer.go
events/events.go
events/events_test.go
main.go

This is to avoid overloading Serf with messages

Condense stats + streams events

---

handlers/accesscontrol/access-control.go

Reverts livepeer/catalyst-api#1047

Revert "access-control: send jwt in gate request"

---

handlers/accesscontrol/access-control.go
handlers/misttriggers/triggers.go
handlers/misttriggers/user_new.go
log/clog.go
middleware/gating.go

Also demonstrated their use in the USER_NEW JWT flow.

log: add more contextual logging capabilities

---

video/transmux.go

This solves the issue with audio/video sync.
Fix https://linear.app/livepeer/issue/PS-198/hello-team-we-have-received-reports-of-audio-sync-issues-in-the-final#comment-c1a08e6e

Re-encode audio while concatenating TS files into MP4

---

clients/object_store_client.go
go.mod
go.sum
metrics/metrics.go

This is useful to confirm private asset playback is going to storj

Add bucket tag to object store metrics

---

handlers/accesscontrol/access-control.go
handlers/accesscontrol/access-control_test.go

This reverts commit 94607ce78d26fb9e534712dec56b1f8673c7a82a.

Revert "access-control: implement in-memory rate limiting (#986)"

---

handlers/accesscontrol/access-control.go

This is to stop us having multiple periodic refresh threads and caches spawned

Make access control handler a singleton

---

transcode/transcode.go
transcode/transcode_test.go

If the first segment is dropped due to a large offset between the a/v track and it happens to be the only segment in the stream (e.g. very short recording), then flag it as an error that will be excused instead of resulting in a panic when attempting to access an empty slice.
Fix PS-273

transcode: handle a/v offset case for short recordings

---

handlers/geolocation/geolocation.go

Because of Easter Holidays, I plan to merge and deploy it on Tuesday, April 2nd.

Remove feature flag for the stream duplication fix

---

balancer/mist/mist_balancer.go
clients/broadcaster_remote.go
clients/input_copy.go
clients/manifest.go
handlers/geolocation/geolocation.go
mapic/utils/seekinghttp.go
thumbnails/thumbnails.go
transcode/transcode.go

I used a vet for the http.Response but manually searched for the io.ReadCloser occurrencies, so
might still have missed some. A lot of cleanups tho, so this should already help.

Make sure we close all http.Response and io.ReadCloser objs

---

handlers/analytics/log_ext_data.go
main.go
mapic/mistapiconnector_app.go
mapic/mistapiconnector_app_test.go
metrics/metrics.go
metrics/monitor_request.go
scripts/pod-mon.sh

This reverts commit f7c4c12492a567f29d2f5e09713a4291cdff94f6.

Revert "(#1281) (#1285) (#1288) (6b1a1536e5422ed81a94e3c6d9deffbfb8a7b53a)"

---

Makefile
clients/broadcaster.go
clients/broadcaster_local.go
clients/broadcaster_local_test.go
clients/broadcaster_remote.go
clients/broadcaster_remote_test.go
clients/mediaconvert.go
go.sum
transcode/transcode.go
transcode/transcode_test.go
video/profiles.go
video/profiles_test.go

transcode,video: Add support for copying HLS input segments

---

handlers/accesscontrol/access-control.go

I changed the order of the checks, so now we first check if the gate allows the playback and only after we check the viewer limit.
There was an issue with the previous behavior that if the viewerLimit is exceeded than the `GetPlaybackAccessControlInfo()` was never called, which in result didn't allow changing the user's `viewerLimit` while the limit is already exceeded.

Fix changing the viewerLimit while viewerLimit is changed

---

balancer/mist/mist_balancer.go
cluster/cluster.go
main.go

Revert changes to MistUtilLoad behavior

---

api/http.go
api/http_internal.go
cluster/cluster.go
config/cli.go
handlers/analytics/log_ext_data.go
handlers/events.go
handlers/events_test.go
handlers/geolocation/geolocation.go
handlers/geolocation/geolocation_test.go
main.go
mapic/mistapiconnector_app.go
mapic/utils.go
mapic/utils_test.go

The catalyst E2E tests are failing. I want to revert to not rush with investigation.
https://github.com/livepeer/catalyst/actions/runs/10042071305/job/27751629774

Revert recent PRs (fix Catalyst build failure)

---

thumbnails/thumbnails.go

- Add a q:v flag of `2` to processSegment to increase the thumbnails quality

thumbnails: q:v quality flag

---

mapic/mistmetrics.go

During the catalyst deployment, we sometimes lost the catalyst-api metrics, because we had no timeout and the `/metrics` endpoint was waiting forever when the Mist was down. 
This PR adds a simple timeout

Add timeout for fetching Mist metrics from catalyst-api

---

.github/workflows/docker.yaml

It makes the CI build very slow

Remove Docker image build for linux/arm64

---

pipeline/coordinator.go

Trying to understand where the jobs are hanging

Add clipping logging

---

pipeline/coordinator.go

Interim Fix: Don't try and use the backup for clipping - this causes a big slowness where we hang for a long time inside this method. Root cause needs to be established, but current thinking is that it happens when there's a very large input manifest

Don't check backup manifest when clipping

---

api/http.go
api/http_internal.go
config/cli.go
handlers/analytics/kafka.go
handlers/analytics/log_processor.go
handlers/analytics/user_end.go
handlers/misttriggers/user_end.go
main.go

For the context, we experience overload on the Postgres DB, so we plan to move this part to Kafka + BigQuery/Clickhouse

Add sending USER_END events to Kafka

---

main.go

Quick nil pointer fix! Not sure how I managed to make this mistake as I tested it in staging, but that must have been a version before I introduced this problem.

Fix catabalancer nil pointer
